### ISSUE TITLE
bug: ALTER table DROP primary key is forbidden

### ISSUE THREAD

**Issue by davidshiz** [stoneatom/stonedb#1034]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```shell
mysql> create table t1 (id int primary key);
Query OK, 0 rows affected (0.41 sec)

mysql> alter table t1 drop primary key;
ERROR 2233 (HY000): Be disgraceful to storage engine, operating is forbidden!
```

### Expected behavior

```shell
mysql> create table t1 (id int primary key);
Query OK, 0 rows affected (0.01 sec)

mysql> alter table t1 drop primary key;
Query OK, 0 rows affected (0.01 sec)
Records: 0  Duplicates: 0  Warnings: 0
```

### How To Reproduce

```sql
create table t1 (id int primary key);
alter table t1 drop primary key;
```

### Environment

```shell
[root@HAST04 ~]# /stonedb57/install/bin/mysqld --version
/stonedb57/install/bin/mysqld  Ver 5.7.36-StoneDB for Linux on x86_64 (build-)
build information as follow:
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: 7f69d33
        Last commit time: Date:   Tue Nov 22 06:31:04 2022 +0000
        Build time: Date: Tue Nov 22 16:53:27 CST 2022
[root@HAST04 ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
```

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by adofsauron** [comment]
ACK

**Comment by adofsauron** [comment]
### Execution stack for alarm:
![lALPGTO6nex-H-3NB1XNDas_3499_1877](https://user-images.githubusercontent.com/3915817/205222962-5ef42cdd-9ad8-440c-a6bd-2959441c5734.png)


```c++

(gdb) bt
#0  THD::send_statement_status (this=0x7f0c18006f20) at /home/jenkins/workspace/stonedb5.7-zsl-centos7.9-75-133/sql/sql_class.cc:4799
#1  0x00000000023a6a1b in dispatch_command (thd=0x7f0c18006f20, com_data=0x7f0dfeabd730, command=COM_QUERY) at /home/jenkins/workspace/stonedb5.7-zsl-centos7.9-75-133/sql/sql_parse.cc:1912
#2  0x00000000023a4445 in do_command (thd=0x7f0c18006f20) at /home/jenkins/workspace/stonedb5.7-zsl-centos7.9-75-133/sql/sql_parse.cc:1034
#3  0x00000000024d5ad9 in handle_connection (arg=0x878fe70) at /home/jenkins/workspace/stonedb5.7-zsl-centos7.9-75-133/sql/conn_handler/connection_handler_per_thread.cc:313
#4  0x0000000002ba2e22 in pfs_spawn_thread (arg=0x8169180) at /home/jenkins/workspace/stonedb5.7-zsl-centos7.9-75-133/storage/perfschema/pfs.cc:2197
#5  0x00007f0e0946d1ca in start_thread () from /lib64/libpthread.so.0
#6  0x00007f0e067bfe73 in clone () from /lib64/libc.so.6


```

**Comment by adofsauron** [comment]
### Self-test completed, repairable

```sql

mysql> show create table t1\G
*************************** 1. row ***************************
       Table: t1
Create Table: CREATE TABLE `t1` (
  `id` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=TIANMU DEFAULT CHARSET=utf8mb4
1 row in set (0.00 sec)

mysql> alter table t1 drop primary key;
Query OK, 0 rows affected (0.01 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> show create table t1\G
*************************** 1. row ***************************
       Table: t1
Create Table: CREATE TABLE `t1` (
  `id` int(11) NOT NULL
) ENGINE=TIANMU DEFAULT CHARSET=utf8mb4
1 row in set (0.00 sec)


```

**Comment by adofsauron** [comment]
Only one problem is handled at a time. This problem is about deleting the primary key. Other problems are not recorded in this ISSUE
