### ISSUE TITLE
bug: The mysqld server crash when a left join and group by query is executed at Large amount of data and disk In abundance

### ISSUE THREAD

**Issue by haitaoguan** [stoneatom/stonedb#1110]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```sql
create table A(id int,UnitSN varchar(10),CTIME datetime);
insert into A values(1,'A1','2022-12-09 01:00:00');
insert into A values(2,'A2','2022-12-09 02:00:00');
insert into A values(3,'A3','2022-12-09 03:00:00');
insert into A values(4,'A4','2022-12-09 04:00:00');
insert into A values(5,'A5','2022-12-09 05:00:00');
insert into A values(6,'A6','2022-12-09 06:00:00');
insert into A values(7,'A7','2022-12-09 07:00:00');
insert into A values(8,'A8','2022-12-09 08:00:00');
insert into A values(9,'A9','2022-12-09 09:00:00');
insert into A values(10,'A10','2022-12-09 10:00:00');
insert into A values(11,'A11','2022-12-09 11:00:00');
insert into A values(12,'A12','2022-12-09 12:00:00');
insert into A values(13,'A13','2022-12-09 13:00:00');
insert into A values(14,'A14','2022-12-09 14:00:00');
insert into A values(15,'A15','2022-12-09 15:00:00');
insert into A values(16,'A16','2022-12-09 16:00:00');
insert into A values(17,'A17','2022-12-09 17:00:00');
insert into A values(18,'A18','2022-12-09 18:00:00');
insert into A values(19,'A19','2022-12-09 19:00:00');
insert into A values(20,'A20','2022-12-09 20:00:00');
insert into A select * from A;
......
mysql> select count(*) from A;
+----------+
| count(*) |
+----------+
|    20480 |
+----------+
1 row in set (0.00 sec)

create table B(id int,AID int,Name varchar(10),value varchar(10));
insert into B values(1,1,'V1','XXXXXXX1');
insert into B values(2,1,'V2','XXXXXXX2');
insert into B values(3,1,'V3','XXXXXXX3');
insert into B values(4,1,'V4','XXXXXXX4');
insert into B values(5,1,'V5','XXXXXXX5');
insert into B values(6,2,'V6','XXXXXXX6');
insert into B values(7,2,'V7','XXXXXXX7');
insert into B values(8,2,'V8','XXXXXXX8');
insert into B values(9,2,'V9','XXXXXXX9');
insert into B values(10,2,'V10','XXXXXXX10');
insert into B values(11,3,'V11','XXXXXXX11');
insert into B values(12,3,'V12','XXXXXXX12');
insert into B values(13,3,'V13','XXXXXXX13');
insert into B values(14,3,'V14','XXXXXXX14');
insert into B values(15,3,'V15','XXXXXXX15');
insert into B values(16,4,'V16','XXXXXXX16');
insert into B values(17,4,'V17','XXXXXXX17');
insert into B values(18,4,'V18','XXXXXXX18');
insert into B values(19,4,'V19','XXXXXXX19');
insert into B values(20,4,'V20','XXXXXXX20');
insert into B values(21,5,'V21','XXXXXXX21');
insert into B values(22,5,'V22','XXXXXXX22');
insert into B values(23,5,'V23','XXXXXXX23');
insert into B values(24,5,'V24','XXXXXXX24');
insert into B values(25,5,'V25','XXXXXXX25');
insert into B values(26,6,'V26','XXXXXXX26');
insert into B values(27,6,'V27','XXXXXXX27');
insert into B values(28,6,'V28','XXXXXXX28');
insert into B values(29,6,'V29','XXXXXXX29');
insert into B values(30,6,'V30','XXXXXXX30');
insert into B select * from B;
......
mysql> select count(*) from B;
+----------+
| count(*) |
+----------+
| 10149888 |
+----------+
1 row in set (0.01 sec)

###crash SQL
select a.ID,
       a.UNITSN,
       case upper(b.NAME) when 'V1' then b.VALUE else null end as V1,
       case upper(b.NAME) when 'V2' then b.VALUE else null end as V2,
       case upper(b.NAME) when 'V3' then b.VALUE else null end as V3,
       case upper(b.NAME) when 'V4' then b.VALUE else null end as V4,
       case upper(b.NAME) when 'V5' then b.VALUE else null end as V5
  from A a
  left join B b
    on a.ID = b.AID
 group by a.ID, a.UNITSN;
```

```sql
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139737402230336) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=139737402230336) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=139737402230336, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007f172cb44476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f172cb2a7f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007f172cb2a71b in __assert_fail_base (fmt=0x7f172ccdf150 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=0x55d6b81e6c26 "n < size", file=0x55d6b81e6bf0 "/stonedb/storage/tianmu/core/index_table.h", line=41,
    function=<optimized out>) at ./assert/assert.c:92
#6  0x00007f172cb3be96 in __GI___assert_fail (assertion=0x55d6b81e6c26 "n < size",
    file=0x55d6b81e6bf0 "/stonedb/storage/tianmu/core/index_table.h", line=41,
    function=0x55d6b81e6bb0 "void Tianmu::core::IndexTable::Set64(uint64_t, uint64_t)") at ./assert/assert.c:101
#7  0x000055d6b7b65789 in Tianmu::core::IndexTable::Set64 (this=0x7f1258914150, n=649592832, val=1281)
    at /stonedb/storage/tianmu/core/index_table.h:41
#8  0x000055d6b7b8ac9c in Tianmu::core::MultiIndexBuilder::BuildItem::CommitTableValues (this=0x7f1258937960)
    at /stonedb/storage/tianmu/core/multi_index_builder.cpp:88
#9  0x000055d6b7b94423 in Tianmu::core::ParallelHashJoiner::SubmitJoinedTuple (this=0x7f1258934730, build_item=0x7f1258937960,
    traversed_hash_table=0x7f12580273c0, hash_row=2528968, mit=...) at /stonedb/storage/tianmu/core/parallel_hash_join.cpp:1049
#10 0x000055d6b7b93d06 in Tianmu::core::ParallelHashJoiner::AsyncMatchDim (this=0x7f1258934730, params=0x7f1258935680)
    at /stonedb/storage/tianmu/core/parallel_hash_join.cpp:968
#11 0x000055d6b7b92b4a in Tianmu::core::ParallelHashJoiner::MatchDim (this=0x7f1258934730, mit=...)
    at /stonedb/storage/tianmu/core/parallel_hash_join.cpp:825
#12 0x000055d6b7b8ffae in Tianmu::core::ParallelHashJoiner::ExecuteJoin (this=0x7f1258934730)
    at /stonedb/storage/tianmu/core/parallel_hash_join.cpp:439
#13 0x000055d6b7b8eb51 in Tianmu::core::ParallelHashJoiner::ExecuteJoinConditions (this=0x7f1258934730, cond=...)
    at /stonedb/storage/tianmu/core/parallel_hash_join.cpp:230
#14 0x000055d6b7af4b10 in Tianmu::core::ParameterizedFilter::UpdateJoinCondition (this=0x7f12589270b0, cond=..., tips=...)
    at /stonedb/storage/tianmu/core/parameterized_filter.cpp:651
#15 0x000055d6b7af8e76 in Tianmu::core::ParameterizedFilter::UpdateMultiIndex (this=0x7f12589270b0, count_only=false, limit=-1)
    at /stonedb/storage/tianmu/core/parameterized_filter.cpp:1304
#16 0x000055d6b7719059 in Tianmu::core::Query::Preexecute (this=0x7f1726387f50, qu=..., sender=0x7f125891b730, display_now=true)
    at /stonedb/storage/tianmu/core/query.cpp:795
#17 0x000055d6b76e78de in Tianmu::core::Engine::Execute (this=0x55d6b9bb3370, thd=0x7f1258004d60, lex=0x7f1258007088,
    result_output=0x7f1258026ed0, unit_for_union=0x0) at /stonedb/storage/tianmu/core/engine_execute.cpp:477
#18 0x000055d6b76e6647 in Tianmu::core::Engine::HandleSelect (this=0x55d6b9bb3370, thd=0x7f1258004d60, lex=0x7f1258007088,
    result=@0x7f17263883e8: 0x7f1258026ed0, setup_tables_done_option=0, res=@0x7f17263883dc: 32530,
    optimize_after_tianmu=@0x7f17263883e4: 1, tianmu_free_join=@0x7f17263883e0: 1, with_insert=0)
    at /stonedb/storage/tianmu/core/engine_execute.cpp:238
--Type <RET> for more, q to quit, c to continue without paging--
#19 0x000055d6b78001de in Tianmu::handler::ha_my_tianmu_query (thd=0x7f1258004d60, lex=0x7f1258007088,
    result_output=@0x7f17263883e8: 0x7f1258026ed0, setup_tables_done_option=0, res=@0x7f17263883dc: 32530,
    optimize_after_tianmu=@0x7f17263883e4: 1, tianmu_free_join=@0x7f17263883e0: 1, with_insert=0)
    at /stonedb/storage/tianmu/handler/ha_my_tianmu.cpp:88
#20 0x000055d6b6d838b2 in execute_sqlcom_select (thd=0x7f1258004d60, all_tables=0x7f1258026888) at /stonedb/sql/sql_parse.cc:5217
#21 0x000055d6b6d7c8dd in mysql_execute_command (thd=0x7f1258004d60, first_level=true) at /stonedb/sql/sql_parse.cc:2856
#22 0x000055d6b6d84940 in mysql_parse (thd=0x7f1258004d60, parser_state=0x7f1726389590) at /stonedb/sql/sql_parse.cc:5655
#23 0x000055d6b6d7947f in dispatch_command (thd=0x7f1258004d60, com_data=0x7f1726389e40, command=COM_QUERY)
    at /stonedb/sql/sql_parse.cc:1495
#24 0x000055d6b6d782f6 in do_command (thd=0x7f1258004d60) at /stonedb/sql/sql_parse.cc:1034
#25 0x000055d6b6ec0c28 in handle_connection (arg=0x55d6bf0154f0) at /stonedb/sql/conn_handler/connection_handler_per_thread.cc:313
#26 0x000055d6b760ce89 in pfs_spawn_thread (arg=0x55d6bee76730) at /stonedb/storage/perfschema/pfs.cc:2197
#27 0x00007f172cb96b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#28 0x00007f172cc28a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81

```

### Environment

./mysqld  Ver 5.7.36-StoneDB-debug for Linux on x86_64 (build-)
build information as follow:
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: 2a03448e7
        Last commit time: Date:   Tue Dec 6 10:35:03 2022 +0800
        Build time: Date: Thu 08 Dec 2022 12:45:27 PM UTC

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

**Comment by adofsauron** [comment]
ACK

**Comment by adofsauron** [comment]
If no crash occurs when the data volume is low, you are advised to reduce the priority and focus on handling high-priority problems in the current version

**Comment by adofsauron** [comment]
### Parallel hash join failed occurred when a large number of tests were performed


```sql

mysql> select count(1) from A;
+----------+
| count(1) |
+----------+
|   696320 |
+----------+
1 row in set (0.00 sec)


```

```sql

mysql> select count(1) from B;
+----------+
| count(1) |
+----------+
|   672437 |
+----------+
1 row in set (0.00 sec)


```


```sql

mysql> select a.ID,
    ->        a.UNITSN,
    ->        case upper(b.NAME) when 'V1' then b.VALUE else null end as V1,
    ->        case upper(b.NAME) when 'V2' then b.VALUE else null end as V2,
    ->        case upper(b.NAME) when 'V3' then b.VALUE else null end as V3,
    ->        case upper(b.NAME) when 'V4' then b.VALUE else null end as V4,
    ->        case upper(b.NAME) when 'V5' then b.VALUE else null end as V5
    ->   from A a
    ->   left join B b
    ->     on a.ID = b.AID
    ->  group by a.ID, a.UNITSN limit 10;
ERROR 1105 (HY000): Parallel hash join failed.


```

**Comment by adofsauron** [comment]
```sql

create table tunit(
  id int not null,
  unitsn varchar(20) not null
);

create table tlog(
  id int not null,
  unitid int not null,
  vname varchar(20) not null,
  vval int not null
);

create table tresult(
  unitid int not null,
  v1 int,v2 int,v3 int,v4 int,v5 int,v6 int,v7 int,v8 int,v9 int,v10 int,
  v11 int,v12 int,v13 int,v14 int,v15 int,v16 int,v17 int,v18 int,v19 int,v20 int,
  v21 int,v22 int,v23 int,v24 int,v25 int,v26 int,v27 int,v28 int,v29 int,v30 int,
  v31 int,v32 int,v33 int,v34 int,v35 int,v36 int,v37 int,v38 int,v39 int,v40 int,
  v41 int,v42 int,v43 int,v44 int,v45 int,v46 int,v47 int,v48 int,v49 int,v50 int,
  v51 int,v52 int,v53 int,v54 int,v55 int,v56 int,v57 int,v58 int,v59 int,v60 int,
  v61 int,v62 int,v63 int,v64 int,v65 int,v66 int,v67 int,v68 int,v69 int,v70 int,
  v71 int,v72 int,v73 int,v74 int,v75 int,v76 int,v77 int,v78 int,v79 int,v80 int,
  v81 int,v82 int,v83 int,v84 int,v85 int,v86 int,v87 int,v88 int,v89 int,v90 int,
  v91 int,v92 int,v93 int,v94 int,v95 int,v96 int,v97 int,v98 int,v99 int,v100 int
);

```

**Comment by adofsauron** [comment]
### Parallel hash join The disk is full

![a02ff3d2e20ffd30adad12e800e3cf29](https://user-images.githubusercontent.com/3915817/207765516-e5be9c5e-9fbf-4ef7-bd41-8993805fcb83.png)


```sql

mysql> select a.ID,         a.UNITSN,         case upper(b.NAME) when 'V1' then b.VALUE else null end as V1,         case upper(b.NAME) when 'V2' then b.VALUE else null end as V2,         case upper(b.NAME) when 'V3' then b.VALUE else null end as V3,         case upper(b.NAME) when 'V4' then b.VALUE else null end as V4,         case upper(b.NAME) when 'V5' then b.VALUE else null end as V5     from A a
   left join B b       on a.ID = b.AID   group by a.ID, a.UNITSN limit 10;
ERROR 1105 (HY000): Parallel hash join failed.

```

**Comment by adofsauron** [comment]
### When viewing logs, a disk insufficiency error message is displayed

```bash

[2022-12-14 22:22:12.107476] [2617] [ERROR] [parallel_hash_join.cpp:812] MSG: An exception is caught: I/O operation on cache/JW_INT00000108167E340x7fd4c4.tianmu_tmp failed with error - No space left on device
[2022-12-14 22:22:12.107499] [2617] [ERROR] [parallel_hash_join.cpp:812] MSG: An exception is caught: I/O operation on cache/JW_INT00000131EBD6450x7fd4c4.tianmu_tmp failed with error - No space left on device
[2022-12-14 22:22:12.107512] [2617] [ERROR] [parallel_hash_join.cpp:812] MSG: An exception is caught: I/O operation on cache/JW_INT0000011090E6D60x7fd4c4.tianmu_tmp failed with error - No space left on device


```

**Comment by adofsauron** [comment]
### Burst OOM's stack live

```c++

        /stonedb57/install//bin/mysqld(Tianmu::common::OutOfMemoryException::OutOfMemoryException(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x23) [0x2c8e7a1]
        /stonedb57/install//bin/mysqld(Tianmu::system::CacheableItem::CI_Put(int, unsigned char*, int)+0x6e9) [0x2dccb25]
        /stonedb57/install//bin/mysqld(Tianmu::core::IndexTable::LoadBlock(int)+0x12d) [0x3093d91]
        /stonedb57/install//bin/mysqld(Tianmu::core::IndexTable::Set64(unsigned long, unsigned long)+0xb2) [0x309509e]
        /stonedb57/install//bin/mysqld(Tianmu::core::MultiIndexBuilder::BuildItem::CommitTableValues()+0x223) [0x30b6d4d]
        /stonedb57/install//bin/mysqld(Tianmu::core::ParallelHashJoiner::SubmitJoinedTuple(Tianmu::core::MultiIndexBuilder::BuildItem*, Tianmu::core::TraversedHashTable*, long, Tianmu::core::MIIterator&)+0x178) [0x30bf88c]
        /stonedb57/install//bin/mysqld(Tianmu::core::ParallelHashJoiner::AsyncMatchDim(Tianmu::core::ParallelHashJoiner::MatchTaskParams*)+0xb32) [0x30bf20a]
        /stonedb57/install//bin/mysqld(_ZSt13__invoke_implIlRMN6Tianmu4core18ParallelHashJoinerEFlPNS2_15MatchTaskParamsEERPS2_IRS4_EET_St21__invoke_memfun_derefOT0_OT1_DpOT2_+0x80) [0x30d1a2e]
        /stonedb57/install//bin/mysqld(std::__invoke_result<long (Tianmu::core::ParallelHashJoiner::*&)(Tianmu::core::ParallelHashJoiner::MatchTaskParams*), Tianmu::core::ParallelHashJoiner*&, Tianmu::core::ParallelHashJoiner::MatchTaskParams*&>::type std::__invoke<long (Tianmu::core::ParallelHashJoiner::*&)(Tianmu::core::ParallelHashJoiner::MatchTaskParams*), Tianmu::core::ParallelHashJoiner*&, Tianmu::core::ParallelHashJoiner::MatchTaskParams*&>(long (Tianmu::core::ParallelHashJoiner::*&)(Tianmu::core::ParallelHashJoiner::MatchTaskParams*), Tianmu::core::ParallelHashJoiner*&, Tianmu::core::ParallelHashJoiner::MatchTaskParams*&)+0x57) [0x30d17a1]


```

**Comment by adofsauron** [comment]
### Function for disk IO interaction

 ```c++

void IndexTable::LoadBlock(int b) {
  DEBUG_ASSERT(IsLocked());
  if (buf == nullptr) {  // possible after block caching on disk
    buf = (unsigned char *)alloc(buffer_size_in_bytes, mm::BLOCK_TYPE::BLOCK_TEMPORARY, true);
    if (!buf) {
      TIANMU_LOG(LogCtl_Level::ERROR, "Could not allocate memory for IndexTable(LoadBlock).");
      throw common::OutOfMemoryException();
    }
  } else if (block_changed)
    CI_Put(cur_block, buf);
  DEBUG_ASSERT(buf != nullptr);
  CI_Get(b, buf);
  if (m_conn->Killed())  // from time to time...
    throw common::KilledException();
  max_block_used = std::max(max_block_used, b);
  cur_block = b;
  block_changed = false;
}

```



```c++

void CacheableItem::CI_Put(int block, unsigned char *data, int size) {
  if (block == -1)
    return;
  if (size == -1)
    size = default_block_size_;
  if (size <= 0)
    return;
  for (int i = no_block_; i < block; i++) {  // rare case: the block numbering is not continuous
    // create empty blocks
    file_number_.push_back(-1);
    file_size_.push_back(0);
    file_start_.push_back(0);
  }

  try {
    if (block >= no_block_ || size != file_size_[block]) {
      // create a new block or reallocate the existing one
      if ((long long)(size) + (long long)(max_file_pos_) > 2000000000) {  // the file size limit: 2 GB
        // file becomes too large, start the next one!
        max_file_id_++;
        max_file_pos_ = 0;
      }
      if (block >= no_block_) {
        file_number_.push_back(max_file_id_);
        file_size_.push_back(size);
        file_start_.push_back(max_file_pos_);
        no_block_ = block + 1;
      } else {
        file_number_[block] = max_file_id_;
        file_size_[block] = size;
        file_start_[block] = max_file_pos_;
      }
      cur_file_handle_.Close();
      SetFilename(file_number_[block]);
      if (max_file_pos_ == 0)  // the new file
        cur_file_handle_.OpenCreateEmpty(file_name_);
      else
        cur_file_handle_.OpenReadWrite(file_name_);
      DEBUG_ASSERT(cur_file_handle_.IsOpen());
      cur_file_number_ = file_number_[block];
      max_file_pos_ += size;
    }
    // save the block
    if (file_number_[block] != cur_file_number_) {
      // open the block file
      cur_file_number_ = file_number_[block];
      cur_file_handle_.Close();
      SetFilename(cur_file_number_);
      cur_file_handle_.OpenReadWrite(file_name_);
      DEBUG_ASSERT(cur_file_handle_.IsOpen());
    }

#ifdef FUNCTIONS_EXECUTION_TIMES
    char str[100];
    if (file_size_[block] >= 1_MB)
      std::sprintf(str, "CacheableItem::CI_Put,write(%dMB)", (int)(file_size_[block] / 1_MB));
    else
      std::sprintf(str, "CacheableItem::CI_Put,write(%dKB)", (int)(file_size_[block] / 1_KB));
    FETOperator feto(str);
#endif
    cur_file_handle_.Seek(file_start_[block], SEEK_SET);
    cur_file_handle_.WriteExact((char *)data, file_size_[block]);
  } catch (common::DatabaseException &e) {
    throw common::OutOfMemoryException(e.what());
  }
}

```

**Comment by adofsauron** [comment]
### Write to disk file

![image](https://user-images.githubusercontent.com/3915817/207770983-ded179bf-27b5-4f3e-a3b9-169175cca946.png)

**Comment by adofsauron** [comment]
Procedure for writing cache file

```c++

[2022-12-15 06:41:41.959954] [4414] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT00000054FDDFE40x7f0294.tianmu_tmp 268435456
[2022-12-15 06:41:42.508793] [4415] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT0000005A8EBD2A0x7f0294.tianmu_tmp 268435456
[2022-12-15 06:41:43.115499] [4414] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT000000435CBD270x7f0294.tianmu_tmp 268435456
[2022-12-15 06:41:43.666961] [4415] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT00000072D5A9170x7f0294.tianmu_tmp 268435456
[2022-12-15 06:42:13.595725] [4414] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT00000054FDDFE40x7f0294.tianmu_tmp 268435456
[2022-12-15 06:42:14.068924] [4415] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT0000005A8EBD2A0x7f0294.tianmu_tmp 268435456
[2022-12-15 06:42:14.646998] [4414] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT000000435CBD270x7f0294.tianmu_tmp 268435456
[2022-12-15 06:42:14.795667] [4415] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT00000072D5A9170x7f0294.tianmu_tmp 268435456
[2022-12-15 06:42:44.140835] [4414] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT00000054FDDFE40x7f0294.tianmu_tmp 268435456
[2022-12-15 06:42:44.379420] [4415] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT0000005A8EBD2A0x7f0294.tianmu_tmp 268435456
[2022-12-15 06:42:44.587766] [4414] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT000000435CBD270x7f0294.tianmu_tmp 268435456
[2022-12-15 06:42:44.830565] [4415] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT00000072D5A9170x7f0294.tianmu_tmp 268435456
[2022-12-15 06:43:13.962260] [4414] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT00000054FDDFE40x7f0294.tianmu_tmp 268435456
[2022-12-15 06:43:14.019784] [4415] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT0000005A8EBD2A0x7f0294.tianmu_tmp 268435456
[2022-12-15 06:43:14.092557] [4414] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT000000435CBD270x7f0294.tianmu_tmp 268435456
[2022-12-15 06:43:14.135264] [4415] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT00000072D5A9170x7f0294.tianmu_tmp 268435456
[2022-12-15 06:43:43.462998] [4415] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT0000005A8EBD2A0x7f0294.tianmu_tmp 268435456
[2022-12-15 06:43:43.566727] [4414] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT00000054FDDFE40x7f0294.tianmu_tmp 268435456
[2022-12-15 06:43:43.570591] [4415] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT00000072D5A9170x7f0294.tianmu_tmp 268435456
[2022-12-15 06:43:43.766478] [4414] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT000000435CBD270x7f0294.tianmu_tmp 268435456
[2022-12-15 06:44:13.149293] [4415] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT0000005A8EBD2A0x7f0294.tianmu_tmp 268435456
[2022-12-15 06:44:13.297330] [4415] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT00000072D5A9170x7f0294.tianmu_tmp 268435456
[2022-12-15 06:44:13.362702] [4414] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT00000054FDDFE40x7f0294.tianmu_tmp 268435456
[2022-12-15 06:44:13.452104] [4414] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT000000435CBD270x7f0294.tianmu_tmp 268435456
[2022-12-15 06:44:43.011748] [4415] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT0000005A8EBD2A0x7f0294.tianmu_tmp 268435456
[2022-12-15 06:44:43.109782] [4415] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT00000072D5A9170x7f0294.tianmu_tmp 268435456
[2022-12-15 06:44:43.413921] [4414] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT00000054FDDFE40x7f0294.tianmu_tmp 268435456
[2022-12-15 06:44:43.635463] [4414] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT000000435CBD270x7f0294.tianmu_tmp 268435456
[2022-12-15 06:45:13.251888] [4415] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT0000015A8EBD2A0x7f0294.tianmu_tmp 268435456
[2022-12-15 06:45:13.457533] [4415] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT00000172D5A9170x7f0294.tianmu_tmp 268435456
[2022-12-15 06:45:13.862493] [4414] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT00000154FDDFE40x7f0294.tianmu_tmp 268435456
[2022-12-15 06:45:14.016810] [4414] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT000001435CBD270x7f0294.tianmu_tmp 268435456
[2022-12-15 06:45:43.754579] [4415] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT0000015A8EBD2A0x7f0294.tianmu_tmp 268435456
[2022-12-15 06:45:43.843300] [4415] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT00000172D5A9170x7f0294.tianmu_tmp 268435456
[2022-12-15 06:45:44.572794] [4414] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT00000154FDDFE40x7f0294.tianmu_tmp 268435456
[2022-12-15 06:45:44.673212] [4414] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT000001435CBD270x7f0294.tianmu_tmp 268435456
[2022-12-15 06:46:14.917910] [4415] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT0000015A8EBD2A0x7f0294.tianmu_tmp 268435456
[2022-12-15 06:46:14.998050] [4415] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT00000172D5A9170x7f0294.tianmu_tmp 268435456
[2022-12-15 06:46:15.921873] [4414] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT00000154FDDFE40x7f0294.tianmu_tmp 268435456
[2022-12-15 06:46:16.011032] [4414] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT000001435CBD270x7f0294.tianmu_tmp 268435456
[2022-12-15 06:46:46.245332] [4415] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT0000015A8EBD2A0x7f0294.tianmu_tmp 268435456
[2022-12-15 06:46:46.346144] [4415] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT00000172D5A9170x7f0294.tianmu_tmp 268435456
[2022-12-15 06:46:47.766805] [4414] [INFO] [cacheable_item.cpp:165] MSG: CACHE WRITE cache/JW_INT00000154FDDFE40x7f0294.tianmu_tmp 268435456


```

**Comment by adofsauron** [comment]
The crash occurred when disk space was still free because the internal count used an int type overflowed and crashed

**Comment by adofsauron** [comment]
### Execution Time

It takes 33,792MB of disk space for caching, 33GB, and on a 30.46 machine, it runs 24m5s


![92946BA0-D710-4672-AB8F-98D7C116D7D4](https://user-images.githubusercontent.com/3915817/208073498-f0bcffee-a8d1-4a37-b061-ce725baa4c2b.png)


### The amount of data in the two tables
```sql

mysql> select count(1) from A;
+----------+
| count(1) |
+----------+
|    20480 |
+----------+
1 row in set (0.00 sec)

mysql> 
mysql> select count(1) from B;
+----------+
| count(1) |
+----------+
|  5742592 |
+----------+
1 row in set (0.00 sec)


```


### Result of Execution


```sql

ID	UNITSN	V1	V2	V3	V4	V5
1	A1	XXXXXXX1	NULL	NULL	NULL	NULL
2	A2	NULL	NULL	NULL	NULL	NULL
3	A3	NULL	NULL	NULL	NULL	NULL
4	A4	NULL	NULL	NULL	NULL	NULL
5	A5	NULL	NULL	NULL	NULL	NULL
6	A6	NULL	NULL	NULL	NULL	NULL
7	A7	NULL	NULL	NULL	NULL	NULL
8	A8	NULL	NULL	NULL	NULL	NULL
9	A9	NULL	NULL	NULL	NULL	NULL
10	A10	NULL	NULL	NULL	NULL	NULL
11	A11	NULL	NULL	NULL	NULL	NULL
12	A12	NULL	NULL	NULL	NULL	NULL
13	A13	NULL	NULL	NULL	NULL	NULL
14	A14	NULL	NULL	NULL	NULL	NULL
15	A15	NULL	NULL	NULL	NULL	NULL
16	A16	NULL	NULL	NULL	NULL	NULL
17	A17	NULL	NULL	NULL	NULL	NULL
18	A18	NULL	NULL	NULL	NULL	NULL
19	A19	NULL	NULL	NULL	NULL	NULL
20	A20	NULL	NULL	NULL	NULL	NULL


```

**Comment by adofsauron** [comment]
### Compare the execution plan of innodb engine

```sql

mysql> show create table a\G
*************************** 1. row ***************************
       Table: a
Create Table: CREATE TABLE `a` (
  `id` int(11) DEFAULT NULL,
  `UnitSN` varchar(10) DEFAULT NULL,
  `CTIME` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
1 row in set (0.00 sec)

mysql> show create table b\G
*************************** 1. row ***************************
       Table: b
Create Table: CREATE TABLE `b` (
  `id` int(11) DEFAULT NULL,
  `AID` int(11) DEFAULT NULL,
  `Name` varchar(10) DEFAULT NULL,
  `value` varchar(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
1 row in set (0.00 sec)


```


```sql

mysql>   explain
    ->   select a.ID,
    ->         a.UNITSN,
    ->         case upper(b.NAME) when 'V1' then b.VALUE else null end as V1,
    ->         case upper(b.NAME) when 'V2' then b.VALUE else null end as V2,
    ->         case upper(b.NAME) when 'V3' then b.VALUE else null end as V3,
    ->         case upper(b.NAME) when 'V4' then b.VALUE else null end as V4,
    ->         case upper(b.NAME) when 'V5' then b.VALUE else null end as V5
    ->     from A a
    ->     left join B b
    ->       on a.ID = b.AID
    ->   group by a.ID, a.UNITSN
    ->   \G
*************************** 1. row ***************************
           id: 1
  select_type: SIMPLE
        table: a
   partitions: NULL
         type: ALL
possible_keys: NULL
          key: NULL
      key_len: NULL
          ref: NULL
         rows: 20228
     filtered: 100.00
        Extra: Using temporary; Using filesort
*************************** 2. row ***************************
           id: 1
  select_type: SIMPLE
        table: b
   partitions: NULL
         type: ALL
possible_keys: NULL
          key: NULL
      key_len: NULL
          ref: NULL
         rows: 5725175
     filtered: 100.00
        Extra: Using where; Using join buffer (Block Nested Loop)
2 rows in set, 1 warning (0.00 sec)


```

**Comment by adofsauron** [comment]
Result of running on the INNODB engine in mysql5.7 official

 
![4eb9e3537be75c489ebd8208f410aaae](https://user-images.githubusercontent.com/3915817/208330915-da4ec73c-8890-44b9-a53f-cc5a5f33fe02.png)
