### ISSUE TITLE
feature: make table scan parallel process to reduce execution time 

### ISSUE THREAD

**Issue by adofsauron** [stoneatom/stonedb#1248]

**Comment by adofsauron** [comment]
### Context stack for full table sweep

```cpp

#0  Tianmu::core::TianmuAttr::EvaluatePack_BetweenInt (this=0x7f948c9ec600, mit=..., dim=0, d=...) at /root/work/stonedb-dev-20230116/storage/tianmu/core/tianmu_attr_exqp.cpp:882
#1  0x0000000002d4d1ef in Tianmu::core::TianmuAttr::EvaluatePack (this=0x7f948c9ec600, mit=..., dim=0, d=...) at /root/work/stonedb-dev-20230116/storage/tianmu/core/tianmu_attr_exqp.cpp:63
#2  0x0000000002e0ed84 in Tianmu::vcolumn::SingleColumn::EvaluatePackImpl (this=0x7f948ca1c770, mit=..., desc=...) at /root/work/stonedb-dev-20230116/storage/tianmu/vc/single_column.cpp:182
#3  0x0000000002e222e7 in Tianmu::vcolumn::VirtualColumnBase::EvaluatePack (this=0x7f948ca1c770, mit=..., desc=...) at /root/work/stonedb-dev-20230116/storage/tianmu/vc/virtual_column_base.h:353
#4  0x0000000002fb9746 in Tianmu::core::Descriptor::EvaluatePackImpl (this=0x7f948ca1f460, mit=...) at /root/work/stonedb-dev-20230116/storage/tianmu/core/descriptor.cpp:838
#5  0x0000000002fb9bb6 in Tianmu::core::Descriptor::EvaluatePack (this=0x7f948ca1f460, mit=...) at /root/work/stonedb-dev-20230116/storage/tianmu/core/descriptor.cpp:907
#6  0x000000000303b015 in Tianmu::core::ParameterizedFilter::ApplyDescriptor (this=0x7f948ca1a770, desc_number=0, limit=-1)
    at /root/work/stonedb-dev-20230116/storage/tianmu/core/parameterized_filter.cpp:1639
#7  0x00000000030393ed in Tianmu::core::ParameterizedFilter::UpdateMultiIndex (this=0x7f948ca1a770, count_only=false, limit=-1)
    at /root/work/stonedb-dev-20230116/storage/tianmu/core/parameterized_filter.cpp:1294
#8  0x0000000002cf494d in Tianmu::core::TempTable::ProcessParameters (this=0x7f948ca1a620, mit=..., alias=-2) at /root/work/stonedb-dev-20230116/storage/tianmu/core/temp_table.cpp:1777
#9  0x0000000002e13f7a in Tianmu::vcolumn::SubSelectColumn::PrepareSubqResult (this=0x7f948cddc580, mit=..., exists_only=false)
    at /root/work/stonedb-dev-20230116/storage/tianmu/vc/subselect_column.cpp:388
#10 0x0000000002e14320 in Tianmu::vcolumn::SubSelectColumn::IsNullImpl (this=0x7f948cddc580, mit=...) at /root/work/stonedb-dev-20230116/storage/tianmu/vc/subselect_column.cpp:443
#11 0x0000000002cf9ce2 in Tianmu::vcolumn::VirtualColumnBase::IsNull (this=0x7f948cddc580, mit=...) at /root/work/stonedb-dev-20230116/storage/tianmu/vc/virtual_column_base.h:112
#12 0x00000000030c7bfb in Tianmu::core::ParallelHashJoiner::AsyncTraverseDim (this=0x7f948cd407e0, params=0x7f948cd40490)
    at /root/work/stonedb-dev-20230116/storage/tianmu/core/parallel_hash_join.cpp:626
#13 0x00000000030dc783 in std::__invoke_impl<long, long (Tianmu::core::ParallelHashJoiner::*&)(Tianmu::core::ParallelHashJoiner::TraverseTaskParams*), Tianmu::core::ParallelHashJoiner<Tianmu::core::ParallelHashJoiner::TraverseTaskParams*&>*&> (__f=
    @0x7f948c9f4c08: (long (Tianmu::core::ParallelHashJoiner::*)(Tianmu::core::ParallelHashJoiner * const, Tianmu::core::ParallelHashJoiner::TraverseTaskParams *)) 0x30c7a5a <Tianmu::core::ParallelHashJoiner::AsyncTraverseDim(Tianmu::core::ParallelHashJoiner::TraverseTaskParams*)>, __t=@0x7f948c9f4c20: 0x7f948cd407e0) at /usr/include/c++/8/bits/invoke.h:73
#14 0x00000000030dc511 in std::__invoke<long (Tianmu::core::ParallelHashJoiner::*&)(Tianmu::core::ParallelHashJoiner::TraverseTaskParams*), Tianmu::core::ParallelHashJoiner*&, Tianmu::core::ParallelHashJoiner::TraverseTaskParams*&> (__fn=
    @0x7f948c9f4c08: (long (Tianmu::core::ParallelHashJoiner::*)(Tianmu::core::ParallelHashJoiner * const, Tianmu::core::ParallelHashJoiner::TraverseTaskParams *)) 0x30c7a5a <Tianmu::core::ParallelHashJoiner::AsyncTraverseDim(Tianmu::core::ParallelHashJoiner::TraverseTaskParams*)>) at /usr/include/c++/8/bits/invoke.h:95
#15 0x00000000030dc183 in std::_Bind<long (Tianmu::core::ParallelHashJoiner::*(Tianmu::core::ParallelHashJoiner*, Tianmu::core::ParallelHashJoiner::TraverseTaskParams*))(Tianmu::core::ParallelHashJoiner::TraverseTaskParams*)>::__call<long, , 0ul, 1ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul>) (this=0x7f948c9f4c08, __args=empty std::tuple) at /usr/include/c++/8/functional:400
#16 0x00000000030dbaf8 in std::_Bind<long (Tianmu::core::ParallelHashJoiner::*(Tianmu::core::ParallelHashJoiner*, Tianmu::core::ParallelHashJoiner::TraverseTaskParams*))(Tianmu::core::ParallelHashJoiner::TraverseTaskParams*)>::operator()<, long>() (this=0x7f948c9f4c08) at /usr/include/c++/8/functional:484
#17 0x00000000030db056 in std::__invoke_impl<long, std::_Bind<long (Tianmu::core::ParallelHashJoiner::*(Tianmu::core::ParallelHashJoiner*, Tianmu::core::ParallelHashJoiner::TraverseTaskParams*))(Tianmu::core::ParallelHashJoiner::TraverseTaskParams*)>&>(std::__invoke_other, std::_Bind<long (Tianmu::core::ParallelHashJoiner::*(Tianmu::core::ParallelHashJoiner*, Tianmu::core::ParallelHashJoiner::TraverseTaskParams*))(Tianmu::core::ParallelHashJoiner::TraverseTaskParams*)>&) (__f=...) at /usr/include/c++/8/bits/invoke.h:60
#18 0x00000000030da84e in std::__invoke<std::_Bind<long (Tianmu::core::ParallelHashJoiner::*(Tianmu::core::ParallelHashJoiner*, Tianmu::core::ParallelHashJoiner::TraverseTaskParams*))(Tianmu::core::ParallelHashJoiner::TraverseTaskParams*)>&>(std::_Bind<long (Tianmu::core::ParallelHashJoiner::*(Tianmu::core::ParallelHashJoiner*, Tianmu::core::ParallelHashJoiner::TraverseTaskParams*))(Tianmu::core::ParallelHashJoiner::TraverseTaskParams*)>&) (__fn=...) at /usr/include/c++/8/bits/invoke.h:95
#19 0x00000000030da11b in std::__future_base::_Task_state<std::_Bind<long (Tianmu::core::ParallelHashJoiner::*(Tianmu::core::ParallelHashJoiner*, Tianmu::core::ParallelHashJoiner::TraverseTaskParams*))(Tianmu::core::ParallelHashJoiner::TraverseTaskParams*)>, std::allocator<int>, long ()>::_M_run()::{lambda()#1}::operator()() const (this=0x7f948c9f4be0) at /usr/include/c++/8/future:1421
#20 0x00000000030dbbb1 in std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<long>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<std::_Bind<long (Tianmu::core::ParallelHashJoiner::*(Tianmu::core::ParallelHashJoiner*, Tianmu::core::ParallelHashJoiner::TraverseTaskParams*))(Tianmu::core::ParallelHashJoiner::TraverseTaskParams*)>, std::allocator<int>, long ()>::_M_run()::{lambda()#1}, long>::operator()() const (this=0x7f96f6fec590) at /usr/include/c++/8/future:1339

#21 0x00000000030db0d4 in std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<long>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<std::_Bind<long (Tianmu::core::ParallelHashJoiner::*(Tianmu::core::ParallelHashJoiner*, Tianmu::core::ParallelHashJoiner::TraverseTaskParams*))(Tianmu::core::ParallelHashJoiner::TraverseTaskParams*)>, std::allocator<int>, long ()>::_M_run()::{lambda()#1}, long> >::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/8/bits/std_function.h:283
#22 0x0000000002c4d739 in std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>::operator()() const (this=0x7f96f6fec590)
--Type <RET> for more, q to quit, c to continue without paging--
    at /usr/include/c++/8/bits/std_function.h:687
#23 0x0000000002c47331 in std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) (
    this=0x7f948c9f4be0, __f=0x7f96f6fec590, __did_set=0x7f96f6fec4f7) at /usr/include/c++/8/future:561
#24 0x0000000002c5ca33 in std::__invoke_impl<void, void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2<std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>*> (__f=
    @0x7f96f6fec510: (void (std::__future_base::_State_baseV2::*)(std::__future_base::_State_baseV2 * const, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()> *, bool *)) 0x2c4730a <std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)>, __t=@0x7f96f6fec508: 0x7f948c9f4be0) at /usr/include/c++/8/bits/invoke.h:73
#25 0x0000000002c54fa3 in std::__invoke<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&) (__fn=
    @0x7f96f6fec510: (void (std::__future_base::_State_baseV2::*)(std::__future_base::_State_baseV2 * const, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()> *, bool *)) 0x2c4730a <std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)>) at /usr/include/c++/8/bits/invoke.h:95
#26 0x0000000002c4d336 in std::call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(std::once_flag&, void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&)::{lambda()#1}::operator()() const (this=0x7f96f6fec480)
    at /usr/include/c++/8/mutex:672
#27 0x0000000002c4d3a1 in std::call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(std::once_flag&, void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&)::{lambda()#2}::operator()() const (this=0x0) at /usr/include/c++/8/mutex:677
#28 0x0000000002c4d3b2 in std::call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(std::once_flag&, void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&)::{lambda()#2}::_FUN() () at /usr/include/c++/8/mutex:677
#29 0x00007f978d3abe67 in __pthread_once_slow () from /lib64/libpthread.so.0
#30 0x0000000002c41a55 in __gthread_once (__once=0x7f948c9f4bf8, __func=0x7f978d67db90 <__once_proxy>) at /usr/include/c++/8/x86_64-redhat-linux/bits/gthr-default.h:699
#31 0x0000000002c4d45c in std::call_once<void (std::__future_base::_State_baseV2::*)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*>(std::once_flag&, void (std::__future_base::_State_baseV2::*&&)(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*), std::__future_base::_State_baseV2*&&, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*&&, bool*&&) (__once=..., __f=
    @0x7f96f6fec510: (void (std::__future_base::_State_baseV2::*)(std::__future_base::_State_baseV2 * const, std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter>()> *, bool *)) 0x2c4730a <std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)>) at /usr/include/c++/8/mutex:684
#32 0x0000000002c46f79 in std::__future_base::_State_baseV2::_M_set_result(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>, bool) (
    this=0x7f948c9f4be0, __res=..., __ignore_failure=false) at /usr/include/c++/8/future:401
#33 0x00000000030da17a in std::__future_base::_Task_state<std::_Bind<long (Tianmu::core::ParallelHashJoiner::*(Tianmu::core::ParallelHashJoiner*, Tianmu::core::ParallelHashJoiner::TraverseTaskParams*))(Tianmu::core::ParallelHashJoiner::TraverseTaskParams*)>, std::allocator<int>, long ()>::_M_run() (this=0x7f948c9f4be0) at /usr/include/c++/8/future:1423
#34 0x00000000030b08ad in std::packaged_task<long ()>::operator()() (this=0x7f948cd521b0) at /usr/include/c++/8/future:1556
#35 0x00000000030cdc16 in Tianmu::utils::thread_pool::add_task<long (Tianmu::core::ParallelHashJoiner::*)(Tianmu::core::ParallelHashJoiner::TraverseTaskParams*), Tianmu::core::ParallelHashJoiner*, Tianmu::core::ParallelHashJoiner::TraverseTaskParams*>(long (Tianmu::core::ParallelHashJoiner::*&&)(Tianmu::core::ParallelHashJoiner::TraverseTaskParams*), Tianmu::core::ParallelHashJoiner*&&, Tianmu::core::ParallelHashJoiner::TraverseTaskParams*&&)::{lambda()#1}::operator()() const (this=0x7f948cd826b0) at /root/work/stonedb-dev-20230116/storage/tianmu/util/thread_pool.h:94
--Type <RET> for more, q to quit, c to continue without paging--
#36 0x00000000030d5c2f in std::_Function_handler<void (), Tianmu::utils::thread_pool::add_task<long (Tianmu::core::ParallelHashJoiner::*)(Tianmu::core::ParallelHashJoiner::TraverseTaskParams*), Tianmu::core::ParallelHashJoiner*, Tianmu::core::ParallelHashJoiner::TraverseTaskParams*>(long (Tianmu::core::ParallelHashJoiner::*&&)(Tianmu::core::ParallelHashJoiner::TraverseTaskParams*), Tianmu::core::ParallelHashJoiner*&&, Tianmu::core::ParallelHashJoiner::TraverseTaskParams*&&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/8/bits/std_function.h:297
#37 0x0000000002c4c21e in std::function<void ()>::operator()() const (this=0x7f96f6fec6a0) at /usr/include/c++/8/bits/std_function.h:687
#38 0x0000000002c477db in Tianmu::utils::thread_pool::thread_pool(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)::{lambda()#1}::operator()() const (__closure=0x77e6748) at /root/work/stonedb-dev-20230116/storage/tianmu/util/thread_pool.h:61
#39 0x0000000002c6b690 in std::__invoke_impl<void, Tianmu::utils::thread_pool::thread_pool(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)::{lambda()#1}>(std::__invoke_other, Tianmu::utils::thread_pool::thread_pool(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)::{lambda()#1}&&) (
    __f=...) at /usr/include/c++/8/bits/invoke.h:60
#40 0x0000000002c64a3b in std::__invoke<Tianmu::utils::thread_pool::thread_pool(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)::{lambda()#1}>(std::__invoke_result&&, (Tianmu::utils::thread_pool::thread_pool(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)::{lambda()#1}&&)...) (__fn=...)
    at /usr/include/c++/8/bits/invoke.h:95
#41 0x0000000002c79f94 in std::thread::_Invoker<std::tuple<Tianmu::utils::thread_pool::thread_pool(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)::{lambda()#1}> >::_M_invoke<0ul>(std::_Index_tuple<0ul>) (this=0x77e6748) at /usr/include/c++/8/thread:244
#42 0x0000000002c798e9 in std::thread::_Invoker<std::tuple<Tianmu::utils::thread_pool::thread_pool(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)::{lambda()#1}> >::operator()() (this=0x77e6748) at /usr/include/c++/8/thread:253
#43 0x0000000002c78a20 in std::thread::_State_impl<std::thread::_Invoker<std::tuple<Tianmu::utils::thread_pool::thread_pool(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long)::{lambda()#1}> > >::_M_run() (this=0x77e6740) at /usr/include/c++/8/thread:196
#44 0x00007f978d67eb13 in execute_native_thread_routine () from /lib64/libstdc++.so.6
#45 0x00007f978d3a41ca in start_thread () from /lib64/libpthread.so.0
#46 0x00007f978a2fce73 in clone () from /lib64/libc.so.6


```

**Comment by adofsauron** [comment]
### The time-consuming statistics of q18 show the time-consuming focus

```sql

+--------------------+-----------+------------+-------------+--------------+-----------------+
| c_name             | c_custkey | o_orderkey | o_orderdate | o_totalprice | sum(l_quantity) |
+--------------------+-----------+------------+-------------+--------------+-----------------+
| Customer#000128120 |    128120 |    4722021 | 1994-04-07  |    544089.09 |          323.00 |
| Customer#000144617 |    144617 |    3043270 | 1997-02-12  |    530604.44 |          317.00 |
| Customer#000013940 |     13940 |    2232932 | 1997-04-13  |    522720.61 |          304.00 |
| Customer#000066790 |     66790 |    2199712 | 1996-09-30  |    515531.82 |          327.00 |
| Customer#000046435 |     46435 |    4745607 | 1997-07-03  |    508047.99 |          309.00 |
| Customer#000015272 |     15272 |    3883783 | 1993-07-28  |    500241.33 |          302.00 |
| Customer#000146608 |    146608 |    3342468 | 1994-06-12  |    499794.58 |          303.00 |
| Customer#000096103 |     96103 |    5984582 | 1992-03-16  |    494398.79 |          312.00 |
| Customer#000024341 |     24341 |    1474818 | 1992-11-15  |    491348.26 |          302.00 |
| Customer#000137446 |    137446 |    5489475 | 1997-05-23  |    487763.25 |          311.00 |
+--------------------+-----------+------------+-------------+--------------+-----------------+
10 rows in set (1 min 54.74 sec)


```


```c++

[2023-01-30 04:05:11.964016] [55374] [INFO] [parameterized_filter.cpp:1673] MSG: ApplyDescriptor spend: 23.426006 op: 24 dim: 1 eva_type: sin thread_num: 1 NumOfTuples: 1500000 packs_no: 23 pack_all: 23 eva_sin_num: 23
[2023-01-30 04:06:38.808431] [55374] [INFO] [parameterized_filter.cpp:1673] MSG: ApplyDescriptor spend: 86.843971 op: 24 dim: 2 eva_type: sin thread_num: 1 NumOfTuples: 6001215 packs_no: 92 pack_all: 92 eva_sin_num: 89
[2023-01-30 04:06:38.808507] [55374] [INFO] [parameterized_filter.cpp:1315] MSG: ApplyDescriptor total spend: 110.270531


```

```c++

[2023-01-30 19:33:31.971788] [581392] [INFO] [descriptor.cpp:901] MSG: EvaluatePackImpl subquery spend: 13.447886 op: 24 check_num: 65536
[2023-01-30 19:33:47.178937] [581392] [INFO] [descriptor.cpp:901] MSG: EvaluatePackImpl subquery spend: 15.201159 op: 24 check_num: 65536
[2023-01-30 19:33:59.970372] [581392] [INFO] [descriptor.cpp:901] MSG: EvaluatePackImpl subquery spend: 12.785858 op: 24 check_num: 65536
[2023-01-30 19:34:14.983654] [581392] [INFO] [descriptor.cpp:901] MSG: EvaluatePackImpl subquery spend: 15.007914 op: 24 check_num: 65536


```

**Comment by adofsauron** [comment]
In addition to associated subqueries, there is now a multithreaded implementation of table scanning
