### ISSUE TITLE
bug: The mysqld is crashed when you are starting replication.

### ISSUE THREAD

**Issue by haitaoguan** [stoneatom/stonedb#1523]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```sql
Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7f0337fff700 (LWP 36871)]
0x00007f133e593387 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f133e593387 in raise () from /lib64/libc.so.6
#1  0x00007f133e594a78 in abort () from /lib64/libc.so.6
#2  0x00007f133e58c1a6 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007f133e58c252 in __assert_fail () from /lib64/libc.so.6
#4  0x0000000002e4c446 in Tianmu::mm::TraceableObject::~TraceableObject (this=0x7f0310000a30, __in_chrg=<optimized out>) at /home/Code/GitHub/stonedb/storage/tianmu/mm/traceable_object.cpp:131
#5  0x0000000002d9dae2 in Tianmu::core::Pack::~Pack (this=0x7f0310000a30, __in_chrg=<optimized out>) at /home/Code/GitHub/stonedb/storage/tianmu/core/pack.h:45
#6  0x0000000003096524 in Tianmu::core::PackInt::PackInt (this=0x7f0310000a30, dpn=0x7ef042201e98, pc=..., s=0x7ef272668bc0) at /home/Code/GitHub/stonedb/storage/tianmu/core/pack_int.cpp:33
#7  0x0000000002db4c18 in __gnu_cxx::new_allocator<Tianmu::core::PackInt>::construct<Tianmu::core::PackInt<Tianmu::core::DPN*&, Tianmu::core::ObjectId<(Tianmu::core::COORD_TYPE)0, 3, Tianmu::core::object_id_helper::empty> const&, Tianmu::core::ColumnShare*&> > (this=0x7f0337ffd83f, __p=0x7f0310000a30, __args#0=@0x7f0337ffda28: 0x7ef042201e98, __args#1=..., __args#2=@0x7f058c02b618: 0x7ef272668bc0) at /opt/rh/devtoolset-8/root/usr/include/c++/8/ext/new_allocator.h:136
#8  0x0000000002db371e in std::allocator_traits<std::allocator<Tianmu::core::PackInt> >::construct<Tianmu::core::PackInt<Tianmu::core::DPN*&, Tianmu::core::ObjectId<(Tianmu::core::COORD_TYPE)0, 3, Tianmu::core::object_id_helper::empty> const&, Tianmu::core::ColumnShare*&> > (__a=..., __p=0x7f0310000a30, __args#0=@0x7f0337ffda28: 0x7ef042201e98, __args#1=..., __args#2=@0x7f058c02b618: 0x7ef272668bc0)
    at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/alloc_traits.h:475
#9  0x0000000002db0eb2 in std::_Sp_counted_ptr_inplace<Tianmu::core::PackInt, std::allocator<Tianmu::core::PackInt>, (__gnu_cxx::_Lock_policy)2>::_Sp_counted_ptr_inplace<Tianmu::core::DPN*&, Tianmu::core::ObjectId<(Tianmu::core::COORD_TYPE)0, 3, Tianmu::core::object_id_helper::empty> const&, Tianmu::core::ColumnShare*&> (this=0x7f0310000a20, __a=...) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/shared_ptr_base.h:545
#10 0x0000000002dad91d in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::__shared_count<Tianmu::core::PackInt, std::allocator<Tianmu::core::PackInt>, Tianmu::core::DPN*&, Tianmu::core::ObjectId<(Tianmu::core::COORD_TYPE)0, 3, Tianmu::core::object_id_helper::empty> const&, Tianmu::core::ColumnShare*&> (this=0x7f0337ffda48, __p=@0x7f0337ffda40: 0x0, __a=...) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/shared_ptr_base.h:677
#11 0x0000000002da9c64 in std::__shared_ptr<Tianmu::core::PackInt, (__gnu_cxx::_Lock_policy)2>::__shared_ptr<std::allocator<Tianmu::core::PackInt>, Tianmu::core::DPN*&, Tianmu::core::ObjectId<(Tianmu::core::COORD_TYPE)0, 3, Tianmu::core::object_id_helper::empty> const&, Tianmu::core::ColumnShare*&> (this=0x7f0337ffda40, __tag=...) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/shared_ptr_base.h:1342
#12 0x0000000002da70d9 in std::shared_ptr<Tianmu::core::PackInt>::shared_ptr<std::allocator<Tianmu::core::PackInt>, Tianmu::core::DPN*&, Tianmu::core::ObjectId<(Tianmu::core::COORD_TYPE)0, 3, Tianmu::core::object_id_helper::empty> const&, Tianmu::core::ColumnShare*&> (this=0x7f0337ffda40, __tag=...) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/shared_ptr.h:359
#13 0x0000000002da4b5d in std::allocate_shared<Tianmu::core::PackInt, std::allocator<Tianmu::core::PackInt>, Tianmu::core::DPN*&, Tianmu::core::ObjectId<(Tianmu::core::COORD_TYPE)0, 3, Tianmu::core::object_id_helper::empty> const&, Tianmu::core::ColumnShare*&> (__a=..., __args#0=@0x7f0337ffda28: 0x7ef042201e98, __args#1=..., __args#2=@0x7f058c02b618: 0x7ef272668bc0) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/shared_ptr.h:706
#14 0x0000000002da19ff in std::make_shared<Tianmu::core::PackInt, Tianmu::core::DPN*&, Tianmu::core::ObjectId<(Tianmu::core::COORD_TYPE)0, 3, Tianmu::core::object_id_helper::empty> const&, Tianmu::core::ColumnShare*&> (
    __args#0=@0x7f0337ffda28: 0x7ef042201e98, __args#1=..., __args#2=@0x7f058c02b618: 0x7ef272668bc0) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/shared_ptr.h:722
#15 0x0000000002d94193 in Tianmu::core::TianmuAttr::Fetch (this=0x7f058c02b480, pc=...) at /home/Code/GitHub/stonedb/storage/tianmu/core/tianmu_attr.cpp:870
#16 0x0000000002da1489 in Tianmu::core::DataCache::GetOrFetchObject<Tianmu::core::Pack, Tianmu::core::ObjectId<(Tianmu::core::COORD_TYPE)0, 3, Tianmu::core::object_id_helper::empty>, Tianmu::core::TianmuAttr> (this=0xa1a05fa0, 
    coord_=..., fetcher_=0x7f058c02b480) at /home/Code/GitHub/stonedb/storage/tianmu/core/data_cache.h:234
#17 0x0000000002d938b6 in Tianmu::core::TianmuAttr::LockPackForUse (this=0x7f058c02b480, pn=88) at /home/Code/GitHub/stonedb/storage/tianmu/core/tianmu_attr.cpp:797
#18 0x0000000002d968ba in Tianmu::core::TianmuAttr::<lambda()>::operator()(void) const (__closure=0x7f0337ffded0) at /home/Code/GitHub/stonedb/storage/tianmu/core/tianmu_attr.cpp:1200
#19 0x0000000002d9adf7 in std::_Function_handler<void(), Tianmu::core::TianmuAttr::DeleteBatchData(Tianmu::core::Transaction*, const std::vector<long unsigned int>&)::<lambda()> >::_M_invoke(const std::_Any_data &) (__functor=...)
    at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/std_function.h:297
#20 0x0000000002cc4ed2 in std::function<void ()>::operator()() const (this=0x7f0337ffded0) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/std_function.h:687
#21 0x0000000002cfceb7 in Tianmu::core::FunctionExecutor::FunctionExecutor(std::function<void ()>, std::function<void ()>) (this=0x7f0337ffdd50, call_in_constructor=..., call_in_deconstructor=...)
    at /home/Code/GitHub/stonedb/storage/tianmu/core/tools.h:271
#22 0x0000000002d96be1 in Tianmu::core::TianmuAttr::DeleteBatchData (this=0x7f058c02b480, tx=0x7f058c0143f0, rows=std::vector of length 3, capacity 3 = {...}) at /home/Code/GitHub/stonedb/storage/tianmu/core/tianmu_attr.cpp:1200
#23 0x0000000002e02667 in std::__invoke_impl<void, void (Tianmu::core::TianmuAttr::*&)(Tianmu::core::Transaction*, std::vector<unsigned long, std::allocator<unsigned long> > const&), Tianmu::core::TianmuAttr<Tianmu::core::Transaction*&, std::vector<unsigned long, std::allocator<unsigned long> >&>*&> (__f=
    @0x7f058c02f2f8: (void (Tianmu::core::TianmuAttr::*)(Tianmu::core::TianmuAttr * const, Tianmu::core::Transaction *, const std::vector<unsigned long, std::allocator<unsigned long> > &)) 0x2d968e6 <Tianmu::core::TianmuAttr::DeleteBatchData(Tianmu::core::Transaction*, std::vector<unsigned long, std::allocator<unsigned long> > const&)>, __t=@0x7f058c02f328: 0x7f058c02b480, __args#0=@0x7f058c02f320: 0x7f058c0143f0, __args#1=std::vector of length 3, capacity 3 = {...})
    at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/invoke.h:73
#24 0x0000000002e01fed in std::__invoke<void (Tianmu::core::TianmuAttr::*&)(Tianmu::core::Transaction*, std::vector<unsigned long, std::allocator<unsigned long> > const&), Tianmu::core::TianmuAttr*&, Tianmu::core::Transaction*&, std::vector<unsigned long, std::allocator<unsigned long> >&> (__fn=
    @0x7f058c02f2f8: (void (Tianmu::core::TianmuAttr::*)(Tianmu::core::TianmuAttr * const, Tianmu::core::Transaction *, const std::vector<unsigned long, std::allocator<unsigned long> > &)) 0x2d968e6 <Tianmu::core::TianmuAttr::DeleteBatchData(Tianmu::core::Transaction*, std::vector<unsigned long, std::allocator<unsigned long> > const&)>, __args#0=@0x7f058c02f328: 0x7f058c02b480, __args#1=@0x7f058c02f320: 0x7f058c0143f0, 
    __args#2=std::vector of length 3, capacity 3 = {...}) at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/invoke.h:95
#25 0x0000000002e01768 in std::_Bind<void (Tianmu::core::TianmuAttr::*(Tianmu::core::TianmuAttr*, Tianmu::core::Transaction*, std::vector<unsigned long, std::allocator<unsigned long> >))(Tianmu::core::Transaction*, std::vector<unsigned long, std::allocator<unsigned long> > const&)>::__call<void, , 0ul, 1ul, 2ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul, 2ul>) (this=0x7f058c02f2f8, __args=empty std::tuple)
    at /opt/rh/devtoolset-8/root/usr/include/c++/8/functional:400
#26 0x0000000002dfffd8 in std::_Bind<void (Tianmu::core::TianmuAttr::*(Tianmu::core::TianmuAttr*, Tianmu::core::Transaction*, std::vector<unsigned long, std::allocator<unsigned long> >))(Tianmu::core::Transaction*, std::vector<unsigned ---Type <return> to continue, or q <return> to quit---
```

### Environment

./mysqld  Ver 5.7.36-StoneDB-v1.0.3 for Linux on x86_64 (build-)
build information as follow: 
        Repository address: https://github.com/stoneatom/stonedb.git:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: 4bd09ac
        Last commit time: Date:   Fri Mar 31 09:43:11 2023 +0800
        Build time: Date: Fri Mar 31 14:02:13 CST 2023

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

**Comment by konghaiya** [comment]
```
[2023-04-11 02:14:31.349637] [42238] [WARN] [exception.cpp:42] MSG: Exception: assert failed on v.HasValue() at pack_str.cpp:198, msg: [./zz/tb_port_run_data.tianmu/columns/11/DATA locationInPack: 0].

STACK TRACE BEGIN
        /home/Code/GitHub/stonedb/build/install//bin/mysqld(Tianmu::common::AssertException::AssertException(char const*, char const*, int, std::string const&)+0x1b7) [0x3005171]
        /home/Code/GitHub/stonedb/build/install//bin/mysqld(Tianmu::core::PackStr::UpdateValue(unsigned long, Tianmu::core::Value const&)+0x171) [0x30ccae1]
        /home/Code/GitHub/stonedb/build/install//bin/mysqld(Tianmu::core::TianmuAttr::UpdateBatchData(Tianmu::core::Transaction*, std::unordered_map<unsigned long, std::shared_ptr<Tianmu::core::Value>, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, std::shared_ptr<Tianmu::core::Value> > > > const&)+0x864) [0x2d9d7b6]
        /home/Code/GitHub/stonedb/build/install//bin/mysqld(void std::__invoke_impl<void, void (Tianmu::core::TianmuAttr::*&)(Tianmu::core::Transaction*, std::unordered_map<unsigned long, std::shared_ptr<Tianmu::core::Value>, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, std::shared_ptr<Tianmu::core::Value> > > > const&), Tianmu::core::TianmuAttr*&, Tianmu::core::Transaction*&, std::unordered_map<unsigned long, std::shared_ptr<Tianmu::core::Value>, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, std::shared_ptr<Tianmu::core::Value> > > >&>(std::__invoke_memfun_deref, void (Tianmu::core::TianmuAttr::*&)(Tianmu::core::Transaction*, std::unordered_map<unsigned long, std::shared_ptr<Tianmu::core::Value>, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, std::shared_ptr<Tianmu::core::Value> > > > const&), Tianmu::core::TianmuAttr*&, Tianmu::core::Transaction*&, std::unordered_map<unsigned long, std::shared_ptr<Tianmu::core::Value>, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, std::shared_ptr<Tianmu::core::Value> > > >&)+0x98) [0x2e0ac53]
        /home/Code/GitHub/stonedb/build/install//bin/mysqld(std::__invoke_result<void (Tianmu::core::TianmuAttr::*&)(Tianmu::core::Transaction*, std::unordered_map<unsigned long, std::shared_ptr<Tianmu::core::Value>, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, std::shared_ptr<Tianmu::core::Value> > > > const&), Tianmu::core::TianmuAttr*&, Tianmu::core::Transaction*&, std::unordered_map<unsigned long, std::shared_ptr<Tianmu::core::Value>, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, std::shared_ptr<Tianmu::core::Value> > > >&>::type std::__invoke<void (Tianmu::core::TianmuAttr::*&)(Tianmu::core::Transaction*, std::unordered_map<unsigned long, std::shared_ptr<Tianmu::core::Value>, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, std::shared_ptr<Tianmu::core::Value> > > > const&), Tianmu::core::TianmuAttr*&, Tianmu::core::Transaction*&, std::unordered_map<unsigned long, std::shared_ptr<Tianmu::core::Value>, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, std::shared_ptr<Tianmu::core::Value> > > >&>(void (Tianmu::core::TianmuAttr::*&)(Tianmu::core::Transaction*, std::unordered_map<unsigned long, std::shared_ptr<Tianmu::core::Value>, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, std::shared_ptr<Tianmu::core::Value> > > > const&), Tianmu::core::TianmuAttr*&, Tianmu::core::Transaction*&, std::unordered_map<unsigned long, std::shared_ptr<Tianmu::core::Value>, std::hash<unsigned long>, std::equal_to<unsigned long>, std::allocator<std::pair<unsigned long const, std::shared_ptr<Tianmu::core::Value> > > >&)+0x6f) [0x2e0a5e7]
        /home/Code/GitHub/stonedb/build/install//bin/mysqld(void std::_Bind<void (Tianmu::core::TianmuAttr::*(Tianmu::core::TianmuAttr*, Tianmu::cor
[2023-04-11 02:14:31.349887] [42193] [ERROR] [engine.cpp:947] MSG: Roll back query 'LOAD DELAYED INSERT DATA INTO TABLE zz.tb_port_run_data'
[2023-04-11 02:14:31.349934] [42193] [INFO] [transaction.cpp:90] MSG: rollback transaction 6434514500002719.
[2023-04-11 02:14:31.349946] [42193] [INFO] [tianmu_table.cpp:679] MSG: roll back table zz../zz/tb_port_run_data.tianmu
[2023-04-11 02:14:31.350042] [42193] [ERROR] [ha_my_tianmu.cpp:121] MSG: RunLoader Error: Tianmu internal error:assert failed on v.HasValue() at pack_str.cpp:198, msg: [./zz/tb_port_run_data.tianmu/columns/11/DATA locationInPack: 0]

```
