### ISSUE TITLE
bug: The instance occasionally crashes when using semi-join

### ISSUE THREAD

**Issue by haitaoguan** [stoneatom/stonedb#1552]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```sql
select B.e_id, count(A.id)
  from A
 inner join B
    ON B.user_id = A.user_id
 where B.code = 'c8de2be2f1ef4dcb8bd5539aee'
   and A.code = 'c8de2be2f1ef4dcb8bd5539aee'
   and A.user_id in
       (select id
          from C
         where C.code = 'c8de2be2f1ef4dcb8bd5539aee'
           and C.d_flag = '0'
           and C.l_flag = '0')
 group by B.e_id;

(gdb) bt
#0  0x000055dce0e34814 in Tianmu::core::Engine::Convert(int&, long&, Tianmu::types::TianmuDataType&, enum_field_types, bool) ()
#1  0x000055dce0e3c967 in Tianmu::core::ResultSender::SendRecord(std::vector<std::unique_ptr<Tianmu::types::TianmuDataType, std::default_delete<Tianmu::types::TianmuDataType> >, std::allocator<std::unique_ptr<Tianmu::types::TianmuDataType, std::default_delete<Tianmu::types::TianmuDataType> > > > const&) ()
#2  0x000055dce0e3cdf5 in Tianmu::core::ResultSender::Send(Tianmu::core::TempTable::RecordIterator&) ()
#3  0x000055dce0fe9c08 in Tianmu::core::AggregationAlgorithm::MultiDimensionalGroupByScan(Tianmu::core::GroupByWrapper&, long&, long&, Tianmu::core::ResultSender*, bool) ()
#4  0x000055dce0fea680 in Tianmu::core::AggregationAlgorithm::Aggregate(bool, long&, long&, Tianmu::core::ResultSender*) ()
#5  0x000055dce0e6f9b1 in Tianmu::core::TempTable::Materialize(bool, Tianmu::core::ResultSender*, bool) ()
#6  0x000055dce0e3ad76 in Tianmu::core::Engine::Execute(THD*, LEX*, Query_result*, st_select_lex_unit*) ()
#7  0x000055dce0e3bad9 in Tianmu::core::Engine::HandleSelect(THD*, LEX*, Query_result*&, unsigned long, int&, int&, int&, int) ()
#8  0x000055dce0ecbf0a in Tianmu::DBHandler::ha_my_tianmu_query(THD*, LEX*, Query_result*&, unsigned long, int&, int&, int&, int) ()
#9  0x000055dce07d8d48 in execute_sqlcom_select(THD*, TABLE_LIST*) ()
#10 0x000055dce07e0612 in mysql_execute_command(THD*, bool) ()
#11 0x000055dce07e28d5 in mysql_parse(THD*, Parser_state*) ()
#12 0x000055dce07e3712 in dispatch_command(THD*, COM_DATA const*, enum_server_command) ()
#13 0x000055dce07e4cc7 in do_command(THD*) ()
#14 0x000055dce08a4f58 in handle_connection ()
#15 0x000055dce0dab3e8 in pfs_spawn_thread ()
#16 0x00007f2015396b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#17 0x00007f2015428a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

### Environment

./mysqld  Ver 5.7.36-StoneDB-v1.0.3 for Linux on x86_64 (build-)
build information as follow:
        Repository address: https://github.com/stoneatom/stonedb:stonedb-5.7-dev
        Branch name: stonedb-5.7-dev
        Last commit ID: 758bce8a5
        Last commit time: Date:   Mon Apr 10 19:46:20 2023 +0800
        Build time: Date: Tue 11 Apr 2023 03:30:57 AM UTC

### Are you interested in submitting a PR to solve the problem?

- [X] Yes, I will!

**Comment by RingsC** [comment]
@haitaoguan , what's table definition of a, b,c? you can post these defs here, thanks.

**Comment by RingsC** [comment]
Firstly, we disable semijoin in tianmu layout, and re-impl this part in future.
