### ISSUE TITLE
bug: mysqld crash in debug version when exec select query of str between int column

### ISSUE THREAD

**Issue by adofsauron** [stoneatom/stonedb#1603]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```sql

rop table ttt;

create table ttt(c1 int,c2 int);

insert into ttt values(327266,1),(327267,1),(327268,1),(327269,1),(327270,1);


select c1 from ttt union all select 'aaa' c1 from (select c2 from ttt where c1 IN (327266)) x;

```

```cpp


#0  0x00007ff1e0161acf in raise () from /lib64/libc.so.6
#1  0x00007ff1e0134ea5 in abort () from /lib64/libc.so.6
#2  0x00007ff1e0134d79 in __assert_fail_base.cold.0 () from /lib64/libc.so.6
#3  0x00007ff1e015a426 in __assert_fail () from /lib64/libc.so.6
#4  0x0000000002ce5c61 in Tianmu::core::Engine::ConvertToField (field=0x7fe548a3bbf8, tianmu_item=..., blob_buf=0x0)
    at /root/work/stonedb-dev-20230419/storage/tianmu/core/engine_convert.cpp:37
#5  0x0000000002cf1d74 in Tianmu::core::ResultSender::SendRecord (this=0x7fe54815c2a0, r=std::vector of length 1, capacity 1 = {...})
    at /root/work/stonedb-dev-20230419/storage/tianmu/core/engine_results.cpp:300
#6  0x0000000002cf1be5 in Tianmu::core::ResultSender::SendRow (this=0x7fe54815c2a0, record=std::vector of length 1, capacity 1 = {...}, owner=0x7fe548a43670)
    at /root/work/stonedb-dev-20230419/storage/tianmu/core/engine_results.cpp:269
#7  0x0000000002d59e0d in Tianmu::core::TempTable::SendResult (this=0x7fe548a43670, limit=5, offset=0, sender=..., pagewise=false)
    at /root/work/stonedb-dev-20230419/storage/tianmu/core/temp_table_low.cpp:503
#8  0x0000000002d58c95 in Tianmu::core::TempTable::FillMaterializedBuffers (this=0x7fe548a43670, local_limit=5, local_offset=0, sender=0x7fe54815c2a0, pagewise=false)
    at /root/work/stonedb-dev-20230419/storage/tianmu/core/temp_table_low.cpp:317
#9  0x0000000002d3fae1 in Tianmu::core::TempTable::Materialize (this=0x7fe548a43670, in_subq=false, sender=0x7fe54815c2a0, lazy=false)
    at /root/work/stonedb-dev-20230419/storage/tianmu/core/temp_table.cpp:2066
#10 0x0000000002d3d0aa in Tianmu::core::TempTable::Union (this=0x7fe548a43670, t=0x7fe548a48a80, all=1, sender=0x7fe54815c2a0, g_offset=@0x7ff1d8fddea0: 0, g_limit=@0x7ff1d8fddea8: -1)
    at /root/work/stonedb-dev-20230419/storage/tianmu/core/temp_table.cpp:1575
#11 0x0000000002cffe97 in Tianmu::core::Query::Preexecute (this=0x7ff1d8fde7f0, qu=..., sender=0x7fe54815c2a0, display_now=true)
    at /root/work/stonedb-dev-20230419/storage/tianmu/core/query.cpp:882
#12 0x0000000002ceb6a0 in Tianmu::core::Engine::Execute (this=0x53e26e0, thd=0x7fe548145b10, lex=0x7fe548147e38, result_output=0x7fe548155fd8, unit_for_union=0x7fe54814b218)
    at /root/work/stonedb-dev-20230419/storage/tianmu/core/engine_execute.cpp:487
#13 0x0000000002cea35c in Tianmu::core::Engine::HandleSelect (this=0x53e26e0, thd=0x7fe548145b10, lex=0x7fe548147e38, result=@0x7ff1d8fdedc8: 0x7fe548155fd8, setup_tables_done_option=0, 
    res=@0x7ff1d8fdedc4: 0, is_optimize_after_tianmu=@0x7ff1d8fdedbc: 1, tianmu_free_join=@0x7ff1d8fdedc0: 0, with_insert=0)
    at /root/work/stonedb-dev-20230419/storage/tianmu/core/engine_execute.cpp:194
#14 0x0000000003081b26 in Tianmu::DBHandler::ha_my_tianmu_query (thd=0x7fe548145b10, lex=0x7fe548147e38, result_output=@0x7ff1d8fdedc8: 0x7fe548155fd8, setup_tables_done_option=0, 
    res=@0x7ff1d8fdedc4: 0, is_optimize_after_tianmu=@0x7ff1d8fdedbc: 1, tianmu_free_join=@0x7ff1d8fdedc0: 0, with_insert=0)
    at /root/work/stonedb-dev-20230419/storage/tianmu/sql/ha_my_tianmu.cpp:90
#15 0x00000000024278b6 in execute_sqlcom_select (thd=0x7fe548145b10, all_tables=0x7fe548152d80) at /root/work/stonedb-dev-20230419/sql/sql_parse.cc:5204
#16 0x0000000002420c2c in mysql_execute_command (thd=0x7fe548145b10, first_level=true) at /root/work/stonedb-dev-20230419/sql/sql_parse.cc:2847
#17 0x000000000242891b in mysql_parse (thd=0x7fe548145b10, parser_state=0x7ff1d8fdff90) at /root/work/stonedb-dev-20230419/sql/sql_parse.cc:5642
#18 0x000000000241d912 in dispatch_command (thd=0x7fe548145b10, com_data=0x7ff1d8fe0730, command=COM_QUERY) at /root/work/stonedb-dev-20230419/sql/sql_parse.cc:1495
#19 0x000000000241c753 in do_command (thd=0x7fe548145b10) at /root/work/stonedb-dev-20230419/sql/sql_parse.cc:1034
#20 0x000000000254ece9 in handle_connection (arg=0xe31fbe0) at /root/work/stonedb-dev-20230419/sql/conn_handler/connection_handler_per_thread.cc:313
#21 0x0000000002c1e528 in pfs_spawn_thread (arg=0xcecc370) at /root/work/stonedb-dev-20230419/storage/perfschema/pfs.cc:2197
#22 0x00007ff1e34cd1ca in start_thread () from /lib64/libpthread.so.0
#23 0x00007ff1e014ce73 in clone () from /lib64/libc.so.6



```

![image](https://user-images.githubusercontent.com/3915817/233300771-581b8230-536d-4d74-a1e5-a731966e10d2.png)

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by adofsauron** [comment]
The decimal type also crashes under the debug version

 
![355d29f3a60fb264798750d5b8b8c83c](https://user-images.githubusercontent.com/3915817/233303102-43c0208d-2def-4264-b0a1-845ee0935970.png)
