### ISSUE TITLE
bug: myqld crash when query with union all and After assigning a variable to the return field   

### ISSUE THREAD

**Issue by adofsauron** [stoneatom/stonedb#1605]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem
```sql
mysql> create table ttt(c1 decimal(18,0),c2 decimal(18,0));
Query OK, 0 rows affected (0.16 sec)

mysql>  insert into ttt values(3000000000027266,1),(3000000000027267,1),(3000000000027268,1),(3000000000027269,1),(3000000000027270,1);
Query OK, 5 rows affected (0.00 sec)
Records: 5  Duplicates: 0  Warnings: 0

mysql> select * from ttt;
+------------------+------+
| c1               | c2   |
+------------------+------+
| 3000000000027266 |    1 |
| 3000000000027267 |    1 |
| 3000000000027268 |    1 |
| 3000000000027269 |    1 |
| 3000000000027270 |    1 |
+------------------+------+
5 rows in set (0.00 sec)

mysql> select c1,c2 from ttt union all select 'aaa' c1,'bbb' c2 from ttt;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

```cpp

#0  0x00007f66250ca387 in raise () from /lib64/libc.so.6
#1  0x00007f66250cba78 in abort () from /lib64/libc.so.6
#2  0x00007f66250c31a6 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007f66250c3252 in __assert_fail () from /lib64/libc.so.6
#4  0x0000000002d2c968 in Tianmu::core::TempTable::GetColumn (this=0x7f5b492cda80, a=0) at /root/work/stonedb-dev-20230419/storage/tianmu/core/temp_table.h:310
#5  0x0000000002ce84db in Tianmu::core::Query::Preexecute (this=0x7f65d008d730, qu=..., sender=0x7f5b49297fa0, display_now=true)
    at /root/work/stonedb-dev-20230419/storage/tianmu/core/query.cpp:839
#6  0x0000000002cd4586 in Tianmu::core::Engine::Execute (this=0x6d7a3b0, thd=0x7f5b48002b80, lex=0x7f5b48004ea8, result_output=0x7f5b480651e0, unit_for_union=0x7f5b4802a568)
    at /root/work/stonedb-dev-20230419/storage/tianmu/core/engine_execute.cpp:487
#7  0x0000000002cd323b in Tianmu::core::Engine::HandleSelect (this=0x6d7a3b0, thd=0x7f5b48002b80, lex=0x7f5b48004ea8, result=@0x7f65d008dcb8: 0x7f5b480651e0, setup_tables_done_option=0, 
    res=@0x7f65d008dcb4: 0, is_optimize_after_tianmu=@0x7f65d008dcac: 1, tianmu_free_join=@0x7f65d008dcb0: 0, with_insert=0)
    at /root/work/stonedb-dev-20230419/storage/tianmu/core/engine_execute.cpp:194
#8  0x0000000003065f1e in Tianmu::DBHandler::ha_my_tianmu_query (thd=0x7f5b48002b80, lex=0x7f5b48004ea8, result_output=@0x7f65d008dcb8: 0x7f5b480651e0, setup_tables_done_option=0, 
    res=@0x7f65d008dcb4: 0, is_optimize_after_tianmu=@0x7f65d008dcac: 1, tianmu_free_join=@0x7f65d008dcb0: 0, with_insert=0)
    at /root/work/stonedb-dev-20230419/storage/tianmu/sql/ha_my_tianmu.cpp:90
#9  0x00000000024115ec in execute_sqlcom_select (thd=0x7f5b48002b80, all_tables=0x7f5b480443f0) at /root/work/stonedb-dev-20230419/sql/sql_parse.cc:5204
#10 0x000000000240ac6e in mysql_execute_command (thd=0x7f5b48002b80, first_level=true) at /root/work/stonedb-dev-20230419/sql/sql_parse.cc:2847
#11 0x000000000241262b in mysql_parse (thd=0x7f5b48002b80, parser_state=0x7f65d008ee80) at /root/work/stonedb-dev-20230419/sql/sql_parse.cc:5642
#12 0x00000000024079b4 in dispatch_command (thd=0x7f5b48002b80, com_data=0x7f65d008f610, command=COM_QUERY) at /root/work/stonedb-dev-20230419/sql/sql_parse.cc:1495
#13 0x00000000024067fe in do_command (thd=0x7f5b48002b80) at /root/work/stonedb-dev-20230419/sql/sql_parse.cc:1034
#14 0x00000000025389f7 in handle_connection (arg=0xc641f30) at /root/work/stonedb-dev-20230419/sql/conn_handler/connection_handler_per_thread.cc:313
#15 0x0000000002c0781f in pfs_spawn_thread (arg=0xc6be0a0) at /root/work/stonedb-dev-20230419/storage/perfschema/pfs.cc:2197
#16 0x00007f66278d9ea5 in start_thread () from /lib64/libpthread.so.0
#17 0x00007f6625192b0d in clone () from /lib64/libc.so.6


```

![a59987c8b65518424a2645cc6cbfd077](https://user-images.githubusercontent.com/3915817/233318468-ea660444-5423-48bc-9edb-639b939c9010.png)

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by adofsauron** [comment]
```sql

 select c1,c2 from ttt union all select 'aaa' c1,'bbb' c2 from ttt;


  select c1,c2 from ttt union select 'aaa' c1,'bbb' c2 from ttt;


   select c1,c2 from ttt union all select c1, c2 from ttt;

```

**Comment by adofsauron** [comment]
```bash


/opt/stonedb57/install/bin/mysql -uroot -pmysql123 -h127.0.0.1 -D mbs

```

**Comment by adofsauron** [comment]
```bash

/bin/sh /opt/stonedb57/install/bin/mysqld_safe --defaults-file=/opt/stonedb57/install/my.cnf --user=mysql &


```

**Comment by adofsauron** [comment]
```c++


$1 = (Tianmu::core::TempTable) {
  <Tianmu::core::JustATable> = {
    <std::enable_shared_from_this<Tianmu::core::JustATable>> = {
      _M_weak_this = std::weak_ptr<Tianmu::core::JustATable> (use count 2, weak count 1) = {
        get() = 0x7f26812a4b60
      }
    }, 
    members of Tianmu::core::JustATable: 
    _vptr.JustATable = 0x41ba3f8 <vtable for Tianmu::core::TempTable+16>
  }, 
  members of Tianmu::core::TempTable: 
  mem_scale = 5, 
  attr_back_translation = std::map with 0 elements, 
  no_obj = 0, 
  p_power = 16, 
  no_cols = 0, 
  mode = {
    distinct = true, 
    top = false, 
    exists = false, 
    param1 = 0, 
    param2 = -1
  }, 
  attrs = std::vector of length 0, capacity 0, 



```

**Comment by adofsauron** [comment]
```c++


T:-1 = TABLE_ALIAS(T:1,"c1md_company")
T:-2 = TMP_TABLE(T:-1,T:-3,T:-4,T:-5,T:-6,T:-7,T:-8,T:-10,T:4294967285)
T:-3 = TABLE_ALIAS(T:1,"c1md_company")
T:-4 = TABLE_ALIAS(T:0,"c1md_bank_acct")
T:-5 = TABLE_ALIAS(T:1,"c1md_company")
T:-6 = TABLE_ALIAS(T:2,"c1cd_currency")
T:-7 = TABLE_ALIAS(T:3,"c1cd_exchange_rate")
VC:-2.0 = CREATE_VC(T:-2,PHYS_COL(T:-7,A:3))
VC:-2.1 = CREATE_VC(T:-2,PHYS_COL(T:-4,A:19))
C:0 = CREATE_CONDS(T:-2,VC:-2.0,=,VC:-2.1,<null>)
VC:-2.2 = CREATE_VC(T:-2,PHYS_COL(T:-7,A:10))
VC:-2.3 = CREATE_VC(T:-2,EXPR("0"))
C:0.AND(VC:-2.2,=,VC:-2.3,<null>)
VC:-2.4 = CREATE_VC(T:-2,PHYS_COL(T:-7,A:9))
VC:-2.5 = CREATE_VC(T:-2,EXPR("1"))
C:0.AND(VC:-2.4,=,VC:-2.5,<null>)
VC:-2.6 = CREATE_VC(T:-2,PHYS_COL(T:-7,A:5))
VC:-2.7 = CREATE_VC(T:-2,EXPR("now"))
C:0.AND(VC:-2.6,<=,VC:-2.7,<null>)
VC:-2.8 = CREATE_VC(T:-2,PHYS_COL(T:-7,A:6))
VC:-2.9 = CREATE_VC(T:-2,EXPR("now"))
C:1 = CREATE_TREE_CONDS(T:-2,VC:-2.8,>=,VC:-2.9,<null>)
C:1.OR(VC:-2.8,IS nullptr,<null>,<null>)
C:0.AND(C:1)
T:-2.LEFT_JOIN_ON({T:-1,T:-3,T:-4,T:-5,T:-6},{T:-7},C:0)
T:-8 = TABLE_ALIAS(T:4,"c1cd_acct_type")
VC:-2.10 = CREATE_VC(T:-2,PHYS_COL(T:-8,A:2))
VC:-2.11 = CREATE_VC(T:-2,PHYS_COL(T:-4,A:2))
C:2 = CREATE_CONDS(T:-2,VC:-2.10,=,VC:-2.11,<null>)
VC:-2.12 = CREATE_VC(T:-2,PHYS_COL(T:-8,A:3))
VC:-2.13 = CREATE_VC(T:-2,PHYS_COL(T:-4,A:23))
C:2.AND(VC:-2.12,=,VC:-2.13,<null>)
VC:-2.14 = CREATE_VC(T:-2,PHYS_COL(T:-8,A:10))
C:2.AND(VC:-2.14,=,VC:-2.3,<null>)
T:-2.LEFT_JOIN_ON({T:-1,T:-3,T:-4,T:-5,T:-6,T:-7},{T:-8},C:2)
T:-9 = TABLE_ALIAS(T:5,"c1am_acct_day")
T:-10 = TMP_TABLE(T:4294967287)
VC:-10.0 = CREATE_VC(T:-10,PHYS_COL(T:-9,A:3))
A:-1 = T:-10.ADD_COLUMN(VC:-10.0,GROUP_BY,"account_id","ALL")
VC:-10.1 = CREATE_VC(T:-10,PHYS_COL(T:-9,A:14))
A:-2 = T:-10.ADD_COLUMN(VC:-10.1,MAX,"fiscal_date","ALL")
VC:-10.2 = CREATE_VC(T:-10,PHYS_COL(T:-9,A:22))
VC:-10.3 = CREATE_VC(T:-10,EXPR("0"))
C:3 = CREATE_CONDS(T:-10,VC:-10.2,=,VC:-10.3,<null>)
T:-10.ADD_CONDS(C:3,HAVING)
T:-10.APPLY_CONDS()
VC:-2.15 = CREATE_VC(T:-2,PHYS_COL(T:-4,A:0))
VC:-2.16 = CREATE_VC(T:-2,PHYS_COL(T:-10,A:-1))
C:4 = CREATE_CONDS(T:-2,VC:-2.15,=,VC:-2.16,<null>)
T:-2.LEFT_JOIN_ON({T:-1,T:-3,T:-4,T:-5,T:-6,T:-7,T:-8},{T:-10},C:4)
T:-11 = TABLE_ALIAS(T:5,"c1am_acct_day")
VC:-2.17 = CREATE_VC(T:-2,PHYS_COL(T:-11,A:22))
C:5 = CREATE_CONDS(T:-2,VC:-2.17,=,VC:-2.3,<null>)
VC:-2.18 = CREATE_VC(T:-2,PHYS_COL(T:-11,A:3))
C:6 = CREATE_CONDS(T:-2,VC:-2.18,=,VC:-2.16,<null>)
C:5.AND(C:6)
VC:-2.19 = CREATE_VC(T:-2,PHYS_COL(T:-10,A:-2))
VC:-2.20 = CREATE_VC(T:-2,PHYS_COL(T:-11,A:14))
C:7 = CREATE_CONDS(T:-2,VC:-2.20,=,VC:-2.19,<null>)
C:5.AND(C:7)
T:-2.LEFT_JOIN_ON({T:-1,T:-3,T:-4,T:-5,T:-6,T:-7,T:-8,T:-10},{T:-11},C:5)
A:-1 = T:-2.ADD_COLUMN(VC:-2.1,LIST,"currency_id","ALL")
VC:-2.21 = CREATE_VC(T:-2,PHYS_COL(T:-4,A:21))
A:-2 = T:-2.ADD_COLUMN(VC:-2.21,LIST,"currency_name","ALL")
VC:-2.22 = CREATE_VC(T:-2,PHYS_COL(T:-6,A:4))
A:-3 = T:-2.ADD_COLUMN(VC:-2.22,LIST,"taxis_no","ALL")
VC:-2.23 = CREATE_VC(T:-2,PHYS_COL(T:-4,A:3))
A:-4 = T:-2.ADD_COLUMN(VC:-2.23,LIST,"company_id","ALL")
VC:-2.24 = CREATE_VC(T:-2,PHYS_COL(T:-4,A:4))
A:-5 = T:-2.ADD_COLUMN(VC:-2.24,LIST,"account_code","ALL")
VC:-2.25 = CREATE_VC(T:-2,PHYS_COL(T:-4,A:5))
A:-6 = T:-2.ADD_COLUMN(VC:-2.25,LIST,"account_name","ALL")
VC:-2.26 = CREATE_VC(T:-2,PHYS_COL(T:-4,A:8))
A:-7 = T:-2.ADD_COLUMN(VC:-2.26,LIST,"bank_id","ALL")
VC:-2.27 = CREATE_VC(T:-2,PHYS_COL(T:-4,A:10))
A:-8 = T:-2.ADD_COLUMN(VC:-2.27,LIST,"bank_name","ALL")
VC:-2.28 = CREATE_VC(T:-2,PHYS_COL(T:-4,A:12))
A:-9 = T:-2.ADD_COLUMN(VC:-2.28,LIST,"hbank_code","ALL")
VC:-2.29 = CREATE_VC(T:-2,PHYS_COL(T:-4,A:13))
A:-10 = T:-2.ADD_COLUMN(VC:-2.29,LIST,"hbank_name","ALL")
VC:-2.30 = CREATE_VC(T:-2,PHYS_COL(T:-6,A:0))
C:8 = CREATE_CONDS(T:-2,VC:-2.30,=,VC:-2.1,<null>)
VC:-2.31 = CREATE_VC(T:-2,PHYS_COL(T:-5,A:0))
VC:-2.32 = CREATE_VC(T:-2,PHYS_COL(T:-1,A:0))
C:8.AND(VC:-2.31,=,VC:-2.32,<null>)
C:8.AND(VC:-2.23,=,VC:-2.32,<null>)
VC:-2.33 = CREATE_VC(T:-2,PHYS_COL(T:-1,A:2))
VC:-2.34 = CREATE_VC(T:-2,PHYS_COL(T:-3,A:2))
C:8.AND(VC:-2.33,=,VC:-2.34,<null>)
VC:-2.35 = CREATE_VC(T:-2,PHYS_COL(T:-1,A:1))
VC:-2.36 = CREATE_VC(T:-2,PHYS_COL(T:-3,A:1))
C:8.AND(VC:-2.35,=,VC:-2.36,<null>)
VC:-2.37 = CREATE_VC(T:-2,PHYS_COL(T:-4,A:44))
C:8.AND(VC:-2.37,=,VC:-2.3,<null>)
VC:-2.38 = CREATE_VC(T:-2,PHYS_COL(T:-4,A:26))
VC:-2.39 = CREATE_VC(T:-2,EXPR("2"))
VC:-2.40 = CREATE_VC(T:-2,EXPR("4"))
VC:-2.41 = CREATE_VC(T:-2,VIRT_COLS([39,..,40](2 items)))
C:8.AND(VC:-2.38,IN,VC:-2.41,<null>)
VC:-2.42 = CREATE_VC(T:-2,EXPR("1"))
VC:-2.43 = CREATE_VC(T:-2,EXPR("0"))
C:8.AND(VC:-2.42,<>,VC:-2.43,<null>)
VC:-2.44 = CREATE_VC(T:-2,PHYS_COL(T:-1,A:21))
C:8.AND(VC:-2.44,=,VC:-2.3,<null>)
VC:-2.45 = CREATE_VC(T:-2,PHYS_COL(T:-3,A:21))
C:8.AND(VC:-2.45,=,VC:-2.3,<null>)
VC:-2.46 = CREATE_VC(T:-2,PHYS_COL(T:-1,A:17))
C:8.AND(VC:-2.46,<>,VC:-2.5,<null>)
VC:-2.47 = CREATE_VC(T:-2,PHYS_COL(T:-3,A:17))
C:8.AND(VC:-2.47,<>,VC:-2.5,<null>)
VC:-2.48 = CREATE_VC(T:-2,PHYS_COL(T:-3,A:0))
VC:-2.49 = CREATE_VC(T:-2,EXPR("3000000000027265"))
C:8.AND(VC:-2.48,=,VC:-2.49,<null>)
VC:-2.50 = CREATE_VC(T:-2,EXPR("substr"))
VC:-2.51 = CREATE_VC(T:-2,PHYS_COL(T:-3,A:8))
C:8.AND(VC:-2.50,=,VC:-2.51,<null>)
VC:-2.52 = CREATE_VC(T:-2,PHYS_COL(T:-6,A:9))
C:8.AND(VC:-2.52,=,VC:-2.3,<null>)
VC:-2.53 = CREATE_VC(T:-2,PHYS_COL(T:-5,A:21))
C:8.AND(VC:-2.53,=,VC:-2.3,<null>)
T:-2.ADD_CONDS(C:8,HAVING)
T:-2.APPLY_CONDS()
T:-2.MODE(DISTINCT,0,0)
T:-12 = TABLE_ALIAS(T:1,"c1md_company")
T:-13 = TMP_TABLE(T:-12,T:-14,T:-15,T:-16,T:-17,T:-18,T:-19,T:-21,T:4294967274)
T:-14 = TABLE_ALIAS(T:1,"c1md_company")
T:-15 = TABLE_ALIAS(T:0,"c1md_bank_acct")
T:-16 = TABLE_ALIAS(T:1,"c1md_company")
T:-17 = TABLE_ALIAS(T:2,"c1cd_currency")
T:-18 = TABLE_ALIAS(T:3,"c1cd_exchange_rate")
VC:-13.0 = CREATE_VC(T:-13,PHYS_COL(T:-18,A:3))
VC:-13.1 = CREATE_VC(T:-13,PHYS_COL(T:-15,A:19))
C:9 = CREATE_CONDS(T:-13,VC:-13.0,=,VC:-13.1,<null>)
VC:-13.2 = CREATE_VC(T:-13,PHYS_COL(T:-18,A:10))
VC:-13.3 = CREATE_VC(T:-13,EXPR("0"))
C:9.AND(VC:-13.2,=,VC:-13.3,<null>)
VC:-13.4 = CREATE_VC(T:-13,PHYS_COL(T:-18,A:9))
VC:-13.5 = CREATE_VC(T:-13,EXPR("1"))
C:9.AND(VC:-13.4,=,VC:-13.5,<null>)
VC:-13.6 = CREATE_VC(T:-13,PHYS_COL(T:-18,A:5))
VC:-13.7 = CREATE_VC(T:-13,EXPR("now"))
C:9.AND(VC:-13.6,<=,VC:-13.7,<null>)
VC:-13.8 = CREATE_VC(T:-13,PHYS_COL(T:-18,A:6))
VC:-13.9 = CREATE_VC(T:-13,EXPR("now"))
C:10 = CREATE_TREE_CONDS(T:-13,VC:-13.8,>=,VC:-13.9,<null>)
C:10.OR(VC:-13.8,IS nullptr,<null>,<null>)
C:9.AND(C:10)
T:-13.LEFT_JOIN_ON({T:-12,T:-14,T:-15,T:-16,T:-17},{T:-18},C:9)
T:-19 = TABLE_ALIAS(T:4,"c1cd_acct_type")
VC:-13.10 = CREATE_VC(T:-13,PHYS_COL(T:-19,A:2))
VC:-13.11 = CREATE_VC(T:-13,PHYS_COL(T:-15,A:2))
C:11 = CREATE_CONDS(T:-13,VC:-13.10,=,VC:-13.11,<null>)
VC:-13.12 = CREATE_VC(T:-13,PHYS_COL(T:-19,A:3))
VC:-13.13 = CREATE_VC(T:-13,PHYS_COL(T:-15,A:23))
C:11.AND(VC:-13.12,=,VC:-13.13,<null>)
VC:-13.14 = CREATE_VC(T:-13,PHYS_COL(T:-19,A:10))
C:11.AND(VC:-13.14,=,VC:-13.3,<null>)
T:-13.LEFT_JOIN_ON({T:-12,T:-14,T:-15,T:-16,T:-17,T:-18},{T:-19},C:11)
T:-20 = TABLE_ALIAS(T:5,"c1am_acct_day")
T:-21 = TMP_TABLE(T:4294967276)
VC:-21.0 = CREATE_VC(T:-21,PHYS_COL(T:-20,A:3))
A:-1 = T:-21.ADD_COLUMN(VC:-21.0,GROUP_BY,"account_id","ALL")
VC:-21.1 = CREATE_VC(T:-21,PHYS_COL(T:-20,A:14))
A:-2 = T:-21.ADD_COLUMN(VC:-21.1,MAX,"fiscal_date","ALL")
VC:-21.2 = CREATE_VC(T:-21,PHYS_COL(T:-20,A:22))
VC:-21.3 = CREATE_VC(T:-21,EXPR("0"))
C:12 = CREATE_CONDS(T:-21,VC:-21.2,=,VC:-21.3,<null>)
T:-21.ADD_CONDS(C:12,HAVING)
T:-21.APPLY_CONDS()
VC:-13.15 = CREATE_VC(T:-13,PHYS_COL(T:-15,A:0))
VC:-13.16 = CREATE_VC(T:-13,PHYS_COL(T:-21,A:-1))
C:13 = CREATE_CONDS(T:-13,VC:-13.15,=,VC:-13.16,<null>)
T:-13.LEFT_JOIN_ON({T:-12,T:-14,T:-15,T:-16,T:-17,T:-18,T:-19},{T:-21},C:13)
T:-22 = TABLE_ALIAS(T:5,"c1am_acct_day")
VC:-13.17 = CREATE_VC(T:-13,PHYS_COL(T:-22,A:22))
C:14 = CREATE_CONDS(T:-13,VC:-13.17,=,VC:-13.3,<null>)
VC:-13.18 = CREATE_VC(T:-13,PHYS_COL(T:-22,A:3))
C:15 = CREATE_CONDS(T:-13,VC:-13.18,=,VC:-13.16,<null>)
C:14.AND(C:15)
VC:-13.19 = CREATE_VC(T:-13,PHYS_COL(T:-21,A:-2))
VC:-13.20 = CREATE_VC(T:-13,PHYS_COL(T:-22,A:14))
C:16 = CREATE_CONDS(T:-13,VC:-13.20,=,VC:-13.19,<null>)
C:14.AND(C:16)
T:-13.LEFT_JOIN_ON({T:-12,T:-14,T:-15,T:-16,T:-17,T:-18,T:-19,T:-21},{T:-22},C:14)
VC:-13.21 = CREATE_VC(T:-13,PHYS_COL(T:-17,A:0))
C:17 = CREATE_CONDS(T:-13,VC:-13.21,=,VC:-13.1,<null>)
VC:-13.22 = CREATE_VC(T:-13,PHYS_COL(T:-12,A:0))
VC:-13.23 = CREATE_VC(T:-13,PHYS_COL(T:-16,A:0))
C:17.AND(VC:-13.22,=,VC:-13.23,<null>)
VC:-13.24 = CREATE_VC(T:-13,PHYS_COL(T:-15,A:3))
C:17.AND(VC:-13.24,=,VC:-13.23,<null>)
VC:-13.25 = CREATE_VC(T:-13,PHYS_COL(T:-14,A:2))
VC:-13.26 = CREATE_VC(T:-13,PHYS_COL(T:-12,A:2))
C:17.AND(VC:-13.25,=,VC:-13.26,<null>)
VC:-13.27 = CREATE_VC(T:-13,PHYS_COL(T:-14,A:1))
VC:-13.28 = CREATE_VC(T:-13,PHYS_COL(T:-12,A:1))
C:17.AND(VC:-13.27,=,VC:-13.28,<null>)
VC:-13.29 = CREATE_VC(T:-13,PHYS_COL(T:-15,A:44))
C:17.AND(VC:-13.29,=,VC:-13.3,<null>)
VC:-13.30 = CREATE_VC(T:-13,PHYS_COL(T:-15,A:26))
VC:-13.31 = CREATE_VC(T:-13,EXPR("2"))
VC:-13.32 = CREATE_VC(T:-13,EXPR("4"))
VC:-13.33 = CREATE_VC(T:-13,VIRT_COLS([31,..,32](2 items)))
C:17.AND(VC:-13.30,IN,VC:-13.33,<null>)
VC:-13.34 = CREATE_VC(T:-13,EXPR("1"))
VC:-13.35 = CREATE_VC(T:-13,EXPR("0"))
C:17.AND(VC:-13.34,<>,VC:-13.35,<null>)
VC:-13.36 = CREATE_VC(T:-13,EXPR("3000000000027265"))
C:17.AND(VC:-13.23,=,VC:-13.36,<null>)
VC:-13.37 = CREATE_VC(T:-13,PHYS_COL(T:-12,A:21))
C:17.AND(VC:-13.37,=,VC:-13.3,<null>)
VC:-13.38 = CREATE_VC(T:-13,PHYS_COL(T:-14,A:21))
C:17.AND(VC:-13.38,=,VC:-13.3,<null>)
VC:-13.39 = CREATE_VC(T:-13,PHYS_COL(T:-12,A:17))
C:17.AND(VC:-13.39,<>,VC:-13.5,<null>)
VC:-13.40 = CREATE_VC(T:-13,PHYS_COL(T:-14,A:17))
C:17.AND(VC:-13.40,<>,VC:-13.5,<null>)
VC:-13.41 = CREATE_VC(T:-13,PHYS_COL(T:-14,A:0))
C:17.AND(VC:-13.41,=,VC:-13.36,<null>)
VC:-13.42 = CREATE_VC(T:-13,EXPR("substr"))
VC:-13.43 = CREATE_VC(T:-13,PHYS_COL(T:-14,A:8))
C:17.AND(VC:-13.42,=,VC:-13.43,<null>)
VC:-13.44 = CREATE_VC(T:-13,PHYS_COL(T:-17,A:9))
C:17.AND(VC:-13.44,=,VC:-13.3,<null>)
VC:-13.45 = CREATE_VC(T:-13,PHYS_COL(T:-16,A:21))
C:17.AND(VC:-13.45,=,VC:-13.3,<null>)
T:-13.ADD_CONDS(C:17,HAVING)
T:-13.APPLY_CONDS()
T:-13.MODE(DISTINCT,0,0)
T:-23 = TMP_TABLE(T:4294967283)
VC:-23.0 = CREATE_VC(T:-23,PHYS_COL(T:-13,A:0))
A:-1 = T:-23.ADD_COLUMN(VC:-23.0,LIST,"currency_id","ALL")
VC:-23.1 = CREATE_VC(T:-23,PHYS_COL(T:-13,A:0))
A:-2 = T:-23.ADD_COLUMN(VC:-23.1,LIST,"company_id","ALL")
VC:-23.2 = CREATE_VC(T:-23,PHYS_COL(T:-13,A:0))
A:-3 = T:-23.ADD_COLUMN(VC:-23.2,GROUP_BY,"null","ALL")
T:-2 = UNION(T:-2,T:-23,1)
RESULT(T:-2)

```
