### ISSUE TITLE
bug: mysqld crash when query where JOIN::propagate_dependencies

### ISSUE THREAD

**Issue by adofsauron** [stoneatom/stonedb#1628]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```c++


#0  0x00007f7723945acf in raise () from /lib64/libc.so.6
#1  0x00007f7723918ea5 in abort () from /lib64/libc.so.6
#2  0x00007f7723918d79 in __assert_fail_base.cold.0 () from /lib64/libc.so.6
#3  0x00007f772393e426 in __assert_fail () from /lib64/libc.so.6
#4  0x00000000024068c7 in JOIN::init_planner_arrays (this=0x7f6a58069c70) at /root/work/stonedb-dev-20230423/sql/sql_optimizer.cc:5286
#5  0x000000000240606a in JOIN::make_join_plan (this=0x7f6a58069c70) at /root/work/stonedb-dev-20230423/sql/sql_optimizer.cc:5134
#6  0x00000000023faa83 in JOIN::optimize (this=0x7f6a58069c70, phase=OptimizePhase::After_LOJ_Transform) at /root/work/stonedb-dev-20230423/sql/sql_optimizer.cc:402
#7  0x0000000002ced1c9 in st_select_lex_unit::optimize_after_tianmu (this=0x7f6a58055040) at /root/work/stonedb-dev-20230423/storage/tianmu/core/engine_execute.cpp:705
#8  0x0000000002cea89d in Tianmu::core::Engine::HandleSelect (this=0x510a6e0, thd=0x7f6a58032b50, lex=0x7f6a58034e78, result=@0x7f771c7c2dc8: 0x7f6a58064268, 
    setup_tables_done_option=0, res=@0x7f771c7c2dc4: 0, is_optimize_after_tianmu=@0x7f771c7c2dbc: 1, tianmu_free_join=@0x7f771c7c2dc0: 1, with_insert=0)
    at /root/work/stonedb-dev-20230423/storage/tianmu/core/engine_execute.cpp:303
#9  0x0000000003082e60 in Tianmu::DBHandler::ha_my_tianmu_query (thd=0x7f6a58032b50, lex=0x7f6a58034e78, result_output=@0x7f771c7c2dc8: 0x7f6a58064268, 
    setup_tables_done_option=0, res=@0x7f771c7c2dc4: 0, is_optimize_after_tianmu=@0x7f771c7c2dbc: 1, tianmu_free_join=@0x7f771c7c2dc0: 1, with_insert=0)
    at /root/work/stonedb-dev-20230423/storage/tianmu/sql/ha_my_tianmu.cpp:95
#10 0x0000000002427886 in execute_sqlcom_select (thd=0x7f6a58032b50, all_tables=0x7f6a58062158) at /root/work/stonedb-dev-20230423/sql/sql_parse.cc:5204
#11 0x0000000002420bfc in mysql_execute_command (thd=0x7f6a58032b50, first_level=true) at /root/work/stonedb-dev-20230423/sql/sql_parse.cc:2847
#12 0x00000000024288eb in mysql_parse (thd=0x7f6a58032b50, parser_state=0x7f771c7c3f90) at /root/work/stonedb-dev-20230423/sql/sql_parse.cc:5642
#13 0x000000000241d8e2 in dispatch_command (thd=0x7f6a58032b50, com_data=0x7f771c7c4730, command=COM_QUERY) at /root/work/stonedb-dev-20230423/sql/sql_parse.cc:1495
#14 0x000000000241c723 in do_command (thd=0x7f6a58032b50) at /root/work/stonedb-dev-20230423/sql/sql_parse.cc:1034
#15 0x000000000254ecb9 in handle_connection (arg=0xe105140) at /root/work/stonedb-dev-20230423/sql/conn_handler/connection_handler_per_thread.cc:313
#16 0x0000000002c1e4f8 in pfs_spawn_thread (arg=0xdab5430) at /root/work/stonedb-dev-20230423/storage/perfschema/pfs.cc:2197
#17 0x00007f7726cb11ca in start_thread () from /lib64/libpthread.so.0
#18 0x00007f7723930e73 in clone () from /lib64/libc.so.6


```

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by adofsauron** [comment]
```cpp


bool JOIN::init_planner_arrays()
{
  // Up to one extra slot per semi-join nest is needed (if materialized)
  const uint sj_nests= select_lex->sj_nests.elements;
  const uint table_count= select_lex->leaf_table_count;
  

  assert(primary_tables == 0 && tables == 0);


```

**Comment by adofsauron** [comment]
```cpp

#4  0x00000000024068c7 in JOIN::init_planner_arrays (this=0x7f6a58069c70) at /root/work/stonedb-dev-20230423/sql/sql_optimizer.cc:5286
5286	  assert(primary_tables == 0 && tables == 0);
(gdb) p primary_tables
$1 = 7
(gdb) p tables
$2 = 7


```

**Comment by adofsauron** [comment]
![223C719D-AEC4-4508-8B52-5962633D5D01](https://user-images.githubusercontent.com/3915817/234533737-a1ae2adc-792d-46d6-a097-02e3e5c89cd6.png)

**Comment by adofsauron** [comment]
```json


 {
  "query_block": {
    "select_id": 1,
    "cost_info": {
      "query_cost": "172.50"
    },
    "nested_loop": [
      {
        "table": {
          "table_name": "r",
          "access_type": "system",
          "rows_examined_per_scan": 1,
          "rows_produced_per_join": 1,
          "filtered": "100.00",
          "cost_info": {
            "read_cost": "0.00",
            "eval_cost": "0.20",
            "prefix_cost": "0.00",
            "data_read_per_join": "16"
          },
          "used_columns": [
            "@rowno := NULL",
            "@rankno := 0"
          ],
          "materialized_from_subquery": {
            "using_temporary_table": true,
            "dependent": false,
            "cacheable": true,
            "query_block": {
              "select_id": 4,
              "message": "No tables used"
            }
          }
        }
      },
      {
        "table": {
          "table_name": "a",
          "access_type": "ALL",
          "rows_examined_per_scan": 650,
          "rows_produced_per_join": 650,
          "filtered": "100.00",
          "cost_info": {
            "read_cost": "42.50",
            "eval_cost": "130.00",
            "prefix_cost": "172.50",
            "data_read_per_join": "10K"
          },
          "used_columns": [
            "taxis_no"
          ],
          "materialized_from_subquery": {
            "using_temporary_table": true,
            "dependent": false,
            "cacheable": true,
            "query_block": {
              "select_id": 2,
              "cost_info": {
                "query_cost": "1068.67"
              },
              "nested_loop": [
                {
                  "table": {
                    "table_name": "a",
                    "access_type": "ALL",
                    "rows_examined_per_scan": 1016,
                    "rows_produced_per_join": 20,
                    "filtered": "2.00",
                    "pushed_condition": "((`mbs`.`a`.`DELETED_FLAG` = '0') and (`mbs`.`a`.`ACCT_FLAG` in ('2','4')))(t0) Pckrows: 1, susp. 1 (0 empty 0 full). Conditions: 2",
                    "cost_info": {
                      "read_cost": "259.94",
                      "eval_cost": "4.06",
                      "prefix_cost": "264.00",
                      "data_read_per_join": "314K"
                    },
                    "used_columns": [
                      "ROW_ID",
                      "CURRENCY_ID",
                      "ACCT_FLAG",
                      "DELETED_FLAG"
                    ]
                  }
                },
                {
                  "table": {
                    "table_name": "d",
                    "access_type": "ALL",
                    "possible_keys": [
                      "PRIMARY"
                    ],
                    "rows_examined_per_scan": 33,
                    "rows_produced_per_join": 2,
                    "filtered": "0.30",
                    "pushed_condition": "(`mbs`.`d`.`DELETED_FLAG` = '0')(t0) Pckrows: 1, susp. 1 (0 empty 0 full). Conditions: 2",
                    "using_join_buffer": "Block Nested Loop",
                    "cost_info": {
                      "read_cost": "20.32",
                      "eval_cost": "0.41",
                      "prefix_cost": "288.38",
                      "data_read_per_join": "6K"
                    },
                    "used_columns": [
                      "ROW_ID",
                      "TAXIS_NO",
                      "DELETED_FLAG"
                    ]
                  }
                },
                {
                  "table": {
                    "table_name": "x",
                    "access_type": "ref",
                    "possible_keys": [
                      "<auto_key0>"
                    ],
                    "key": "<auto_key0>",
                    "used_key_parts": [
                      "account_id"
                    ],
                    "key_length": "8",
                    "ref": [
                      "mbs.a.ROW_ID"
                    ],
                    "rows_examined_per_scan": 320,
                    "rows_produced_per_join": 650,
                    "filtered": "100.00",
                    "cost_info": {
                      "read_cost": "650.24",
                      "eval_cost": "130.05",
                      "prefix_cost": "1068.67",
                      "data_read_per_join": "15K"
                    },
                    "used_columns": [
                      "account_id",
                      "fiscal_date"
                    ],
                    "materialized_from_subquery": {
                      "using_temporary_table": true,
                      "dependent": false,
                      "cacheable": true,
                      "query_block": {
                        "select_id": 3,
                        "cost_info": {
                          "query_cost": "1137930.00"
                        },
                        "grouping_operation": {
                          "using_temporary_table": true,
                          "using_filesort": true,
                          "cost_info": {
                            "sort_cost": "325120.00"
                          },
                          "table": {
                            "table_name": "c1am_acct_day",
                            "access_type": "ALL",
                            "rows_examined_per_scan": 3251200,
                            "rows_produced_per_join": 325120,
                            "filtered": "10.00",
                            "pushed_condition": "(`mbs`.`c1am_acct_day`.`DELETED_FLAG` = '0')(t0) Pckrows: 50, susp. 50 (0 empty 0 full). Conditions: 1",
                            "cost_info": {
                              "read_cost": "747786.00",
                              "eval_cost": "65024.00",
                              "prefix_cost": "812810.00",
                              "data_read_per_join": "3G"
                            },
                            "used_columns": [
                              "ROW_ID",
                              "ACCOUNT_ID",
                              "FISCAL_DATE",
                              "DELETED_FLAG"
                            ]
                          }
                        }
                      }
                    }
                  }
                }
              ]
            }
          }
        }
      }
    ]
  }
}



```

**Comment by adofsauron** [comment]
```c++


           id: 1
  select_type: PRIMARY
        table: <derived4>
   partitions: NULL
         type: system
possible_keys: NULL
          key: NULL
      key_len: NULL
          ref: NULL
         rows: 1
     filtered: 100.00
        Extra: NULL
*************************** 2. row ***************************
           id: 1
  select_type: PRIMARY
        table: <derived2>
   partitions: NULL
         type: ALL
possible_keys: NULL
          key: NULL
      key_len: NULL
          ref: NULL
         rows: 650
     filtered: 100.00
        Extra: NULL
*************************** 3. row ***************************
           id: 4
  select_type: DERIVED
        table: NULL
   partitions: NULL
         type: NULL
possible_keys: NULL
          key: NULL
      key_len: NULL
          ref: NULL
         rows: NULL
     filtered: NULL
        Extra: No tables used
*************************** 4. row ***************************
           id: 2
  select_type: DERIVED
        table: a
   partitions: NULL
         type: ALL
possible_keys: NULL
          key: NULL
      key_len: NULL
          ref: NULL
         rows: 1016
     filtered: 2.00
        Extra: Using where with pushed condition ((`mbs`.`a`.`DELETED_FLAG` = '0') and (`mbs`.`a`.`ACCT_FLAG` in ('2','4')))(t0) Pckrows: 1, susp. 1 (0 empty 0 full). Conditions: 2
*************************** 5. row ***************************
           id: 2
  select_type: DERIVED
        table: d
   partitions: NULL
         type: ALL
possible_keys: PRIMARY
          key: NULL
      key_len: NULL
          ref: NULL
         rows: 33
     filtered: 0.30
        Extra: Using where with pushed condition (`mbs`.`d`.`DELETED_FLAG` = '0')(t0) Pckrows: 1, susp. 1 (0 empty 0 full). Conditions: 2; Using join buffer (Block Nested Loop)
*************************** 6. row ***************************
           id: 2
  select_type: DERIVED
        table: <derived3>
   partitions: NULL
         type: ref
possible_keys: <auto_key0>
          key: <auto_key0>
      key_len: 8
          ref: mbs.a.ROW_ID
         rows: 320
     filtered: 100.00
        Extra: NULL
*************************** 7. row ***************************
           id: 3
  select_type: DERIVED
        table: c1am_acct_day
   partitions: NULL
         type: ALL
possible_keys: NULL
          key: NULL
      key_len: NULL
          ref: NULL
         rows: 3251200
     filtered: 10.00
        Extra: Using where with pushed condition (`mbs`.`c1am_acct_day`.`DELETED_FLAG` = '0')(t0) Pckrows: 50, susp. 50 (0 empty 0 full). Conditions: 1; Using temporary; Using filesort


```
