### ISSUE TITLE
bug: stonedb5.7 crash on cnetos7.9 when run explain sql

### ISSUE THREAD

**Issue by adofsauron** [stoneatom/stonedb#211]
### Describe the problem

`

/stonedb57/install/bin/mysql -D tpch -e " explain select
                            o_orderpriority,
                            count(*) as order_count
                        from
                            orders
                        where
                            o_orderdate >= date '1993-07-01'
                            and o_orderdate < date '1993-07-01' + interval '3' month
                            and exists (
                                select
                                    *
                                from
                                    lineitem
                                where
                                    l_orderkey = o_orderkey
                                    and l_commitdate < l_receiptdate
                            )
                        group by
                            o_orderpriority
                        order by
                            o_orderpriority ;"

`

`
(gdb) c
Continuing.
[New Thread 0x7f260263b700 (LWP 7176)]
[New Thread 0x7f26025b9700 (LWP 7177)]

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7f26025b9700 (LWP 7177)]
0x00007f264f79a387 in raise () from /lib64/libc.so.6
(gdb) bt
#0  0x00007f264f79a387 in raise () from /lib64/libc.so.6
#1  0x00007f264f79ba78 in abort () from /lib64/libc.so.6
#2  0x00007f264f7931a6 in __assert_fail_base () from /lib64/libc.so.6
#3  0x00007f264f793252 in __assert_fail () from /lib64/libc.so.6
#4  0x00000000024bae9f in st_select_lex::optimize (this=0x7f238c0103f8, thd=0x7f238c0009a0) at /home/jenkins/workspace/stonedb5.7-zsl-centos7.9-vm/sql/sql_select.cc:1013
#5  0x000000000251b766 in st_select_lex_unit::optimize (this=0x7f238c0107c0, thd=0x7f238c0009a0) at /home/jenkins/workspace/stonedb5.7-zsl-centos7.9-vm/sql/sql_union.cc:710
#6  0x00000000024baf7e in st_select_lex::optimize (this=0x7f238c005dd0, thd=0x7f238c0009a0) at /home/jenkins/workspace/stonedb5.7-zsl-centos7.9-vm/sql/sql_select.cc:1026
#7  0x00000000024b96c3 in handle_query (thd=0x7f238c0009a0, lex=0x7f238c002cc8, result=0x7f238c011f30, added_options=0, removed_options=0, optimize_after_bh=0, free_join_from_bh=0)
    at /home/jenkins/workspace/stonedb5.7-zsl-centos7.9-vm/sql/sql_select.cc:175
#8  0x000000000246f817 in execute_sqlcom_select (thd=0x7f238c0009a0, all_tables=0x7f238c00f670) at /home/jenkins/workspace/stonedb5.7-zsl-centos7.9-vm/sql/sql_parse.cc:5164
#9  0x0000000002468cae in mysql_execute_command (thd=0x7f238c0009a0, first_level=true) at /home/jenkins/workspace/stonedb5.7-zsl-centos7.9-vm/sql/sql_parse.cc:2831
#10 0x00000000024708f3 in mysql_parse (thd=0x7f238c0009a0, parser_state=0x7f26025b7eb0) at /home/jenkins/workspace/stonedb5.7-zsl-centos7.9-vm/sql/sql_parse.cc:5621
#11 0x0000000002465b8b in dispatch_command (thd=0x7f238c0009a0, com_data=0x7f26025b8650, command=COM_QUERY) at /home/jenkins/workspace/stonedb5.7-zsl-centos7.9-vm/sql/sql_parse.cc:1495
#12 0x0000000002464ab7 in do_command (thd=0x7f238c0009a0) at /home/jenkins/workspace/stonedb5.7-zsl-centos7.9-vm/sql/sql_parse.cc:1034
#13 0x00000000025976d3 in handle_connection (arg=0x9799c00) at /home/jenkins/workspace/stonedb5.7-zsl-centos7.9-vm/sql/conn_handler/connection_handler_per_thread.cc:313
#14 0x0000000002c7b304 in pfs_spawn_thread (arg=0x83ad710) at /home/jenkins/workspace/stonedb5.7-zsl-centos7.9-vm/storage/perfschema/pfs.cc:2197
#15 0x00007f265142bea5 in start_thread () from /lib64/libpthread.so.0
#16 0x00007f264f862b0d in clone () from /lib64/libc.so.6

`

![lALPJwKtz9rd7GnNBTfNDM4_3278_1335](https://user-images.githubusercontent.com/3915817/178691764-09a9d6ba-eb91-4fe3-a3e2-ba1c4c02d798.png)

![image](https://user-images.githubusercontent.com/3915817/178690125-5cd89fd6-c013-406f-a86b-cb48cdee9af8.png)

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by adofsauron** [comment]
no more happen on version 5.7
