### ISSUE TITLE
bug: stonedb crashes when executing "start_server_no_digests.test" test case

### ISSUE THREAD

**Issue by lylth** [stoneatom/stonedb#218]
### Describe the problem

stonedb crashes when executing "start_server_no_digests.test" test case

### How To Reproduce

./mtr start_server_no_digests.test

### Environment

centos7.5 
stonedb5.7
The stack information is as follows:
```
#0  0x00007fcd760e5aa1 in pthread_kill () from /lib64/libpthread.so.0
#1  0x00000000027a852c in my_write_core (sig=11) at /opt/litaihong/stonedb/mysys/stacktrace.c:261
#2  0x0000000001d7b7aa in handle_fatal_signal (sig=11) at /opt/litaihong/stonedb/sql/signal_handler.cc:227
#3  <signal handler called>
#4  0x0000000002e28eb6 in std::_Hashtable<std::string, std::pair<std::string const, std::shared_ptr<stonedb::core::RCTable> >, std::allocator<std::pair<std::string const, std::shared_ptr<stonedb::core::RCTable> > >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::_M_bucket_index (this=0x8, __k="./statements_digest/t12",
    __c=11255588310792463084) at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/hashtable.h:631
#5  0x0000000002e28c5c in std::_Hashtable<std::string, std::pair<std::string const, std::shared_ptr<stonedb::core::RCTable> >, std::allocator<std::pair<std::string const, std::shared_ptr<stonedb::core::RCTable> > >, std::__detail::_Select1st, std::equal_to<std::string>, std::hash<std::string>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::find (this=0x8, __k="./statements_digest/t12")
    at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/hashtable.h:1421
#6  0x0000000002e289f9 in std::unordered_map<std::string, std::shared_ptr<stonedb::core::RCTable>, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::shared_ptr<stonedb::core::RCTable> > > >::find (this=0x8,
    __x="./statements_digest/t12") at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/unordered_map.h:923
#7  0x0000000002e2773e in stonedb::core::Transaction::AddTableWRIfNeeded (this=0x0, share=
    std::shared_ptr (count 2, weak 0) 0x7fca64dfd2b0) at /opt/litaihong/stonedb/storage/stonedb/core/transaction.cpp:75
#8  0x00000000030f0398 in stonedb::dbhandler::StonedbHandler::start_stmt (this=0x7fca64da7290, thd=0x7fca6411ba60,
    lock_type=TL_WRITE_CONCURRENT_INSERT) at /opt/litaihong/stonedb/storage/stonedb/handler/stonedb_handler.cpp:1102
#9  0x00000000023eac8d in check_lock_and_start_stmt (thd=0x7fca6411ba60, prelocking_ctx=0x7fca6411dd90, table_list=0x7fca64013278)
    at /opt/litaihong/stonedb/sql/sql_base.cc:6369
#10 0x00000000023ebad1 in lock_tables (thd=0x7fca6411ba60, tables=0x7fca64013278, count=1, flags=0)
    at /opt/litaihong/stonedb/sql/sql_base.cc:6863
#11 0x000000000268c37d in Sql_cmd_insert::mysql_insert (this=0x7fca64013828, thd=0x7fca6411ba60, table_list=0x7fca64013278)
    at /opt/litaihong/stonedb/sql/sql_insert.cc:624
#12 0x000000000269343f in Sql_cmd_insert::execute (this=0x7fca64013828, thd=0x7fca6411ba60)
    at /opt/litaihong/stonedb/sql/sql_insert.cc:3149
#13 0x000000000246b093 in mysql_execute_command (thd=0x7fca6411ba60, first_level=true)
    at /opt/litaihong/stonedb/sql/sql_parse.cc:3619
#14 0x0000000002470e43 in mysql_parse (thd=0x7fca6411ba60, parser_state=0x7fcd6c1b3eb0)
    at /opt/litaihong/stonedb/sql/sql_parse.cc:5621
#15 0x00000000024660db in dispatch_command (thd=0x7fca6411ba60, com_data=0x7fcd6c1b4650, command=COM_QUERY)
    at /opt/litaihong/stonedb/sql/sql_parse.cc:1495
#16 0x0000000002465007 in do_command (thd=0x7fca6411ba60) at /opt/litaihong/stonedb/sql/sql_parse.cc:1034
#17 0x0000000002597c0d in handle_connection (arg=0x76d6540)
    at /opt/litaihong/stonedb/sql/conn_handler/connection_handler_per_thread.cc:313
#18 0x0000000002c7b83e in pfs_spawn_thread (arg=0x76a94d0) at /opt/litaihong/stonedb/storage/perfschema/pfs.cc:2197
#19 0x00007fcd760e0ea5 in start_thread () from /lib64/libpthread.so.0
#20 0x00007fcd74517b0d in clone () from /lib64/libc.so.6


### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by lylth** [comment]
There is no problem in the latest environment
