### ISSUE TITLE
feature(StoneDB 8.0): adapt mtr test cases:issue502-2/issues_tx417/issue496/issue475

### ISSUE THREAD

**Issue by lujiashun** [stoneatom/stonedb#770]
**Is your feature request related to a problem? Please describe.**

adapt mtr test cases:issue502-2/issues_tx417/issue496/issue475
1 issue502-2 will crash when query the view;
2 issue_tx417 will crash in debug version;
3 issue496 will crash in debug version;
4 issue475 result changed from  "2015-11-13 01:01:01.000020" to "2015-11-13 01:01:01.00002";

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lujiashun** [comment]
issue475.test（result file changed from "2015-11-13 01:01:01.000020" to "2015-11-13 01:01:01.00002"）,  current version of stonedb8.0
```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f107a907859 in __GI_abort () at abort.c:79
#2  0x00007f107a907729 in __assert_fail_base (fmt=0x7f107aa9d588 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n",
    assertion=0x561547f70b18 "send_metadata || field_types == nullptr || field_types[field_pos] == MYSQL_TYPE_DECIMAL || field_types[field_pos] == MYSQL_TYPE_BIT || field_types[field_pos] == MYSQL_TYPE_NEWDECIMAL || field_types[fi"...,
    file=0x561547f70288 "/data/codebase/stonedb80/stonedb/sql/protocol_classic.cc", line=3421, function=<optimized out>) at assert.c:92
#3  0x00007f107a918fd6 in __GI___assert_fail (
    assertion=0x561547f70b18 "send_metadata || field_types == nullptr || field_types[field_pos] == MYSQL_TYPE_DECIMAL || field_types[field_pos] == MYSQL_TYPE_BIT || field_types[field_pos] == MYSQL_TYPE_NEWDECIMAL || field_types[fi"...,
    file=0x561547f70288 "/data/codebase/stonedb80/stonedb/sql/protocol_classic.cc", line=3421,
    function=0x561547f70ac0 "virtual bool Protocol_classic::store_string(const char*, size_t, const CHARSET_INFO*)") at assert.c:101
#4  0x00005615451ba9d9 in Protocol_classic::store_string (this=0x7f0b10005040, from=0x7f0b10991690 "2015-11-13 01:01:01.000020", length=26,
    fromcs=0x56154a1bdce0 <my_charset_latin1>) at /data/codebase/stonedb80/stonedb/sql/protocol_classic.cc:3421
#5  0x0000561544f47312 in Item::send (this=0x7f0b10022548, protocol=0x7f0b10005040, buffer=0x7f10240b03b0)
    at /data/codebase/stonedb80/stonedb/sql/item.cc:7263
#6  0x00005615449f8a3c in THD::send_result_set_row (this=0x7f0b10001040, row_items=...) at /data/codebase/stonedb80/stonedb/sql/sql_class.cc:2865
#7  0x00005615451bd46f in Query_result_send::send_data (this=0x7f0b10021d28, thd=0x7f0b10001040, items=...)
    at /data/codebase/stonedb80/stonedb/sql/query_result.cc:100
#8  0x0000561546e11d51 in Tianmu::core::ResultSender::SendRecord (this=0x7f0b10027b00, r=std::vector of length 1, capacity 1 = {...})
    at /data/codebase/stonedb80/stonedb/storage/tianmu/core/engine_results.cpp:352
#9  0x0000561546e116df in Tianmu::core::ResultSender::SendRow (this=0x7f0b10027b00, record=std::vector of length 1, capacity 1 = {...}, owner=
    0x7f0b10990b50) at /data/codebase/stonedb80/stonedb/storage/tianmu/core/engine_results.cpp:259
#10 0x0000561546ed7ac1 in Tianmu::core::TempTable::SendResult (this=0x7f0b10990b50, limit=1, offset=0, sender=..., pagewise=false)
    at /data/codebase/stonedb80/stonedb/storage/tianmu/core/temp_table_low.cpp:482
#11 0x0000561546ed67d2 in Tianmu::core::TempTable::FillMaterializedBuffers (this=0x7f0b10990b50, local_limit=1, local_offset=0, sender=0x7f0b10027b00,
    pagewise=false) at /data/codebase/stonedb80/stonedb/storage/tianmu/core/temp_table_low.cpp:310
#12 0x0000561546ebf1e9 in Tianmu::core::TempTable::Materialize (this=0x7f0b10990b50, in_subq=false, sender=0x7f0b10027b00, lazy=false)
    at /data/codebase/stonedb80/stonedb/storage/tianmu/core/temp_table.cpp:1958
#13 0x0000561546dd6d35 in Tianmu::core::Engine::Execute (this=0x56154e24fdd0, thd=0x7f0b10001040, lex=0x7f0b100043c0, result_output=0x7f0b10021d28,
    unit_for_union=0x0) at /data/codebase/stonedb80/stonedb/storage/tianmu/core/engine.cpp:2347
#14 0x0000561546dd6048 in Tianmu::core::Engine::Handle_Query (this=0x56154e24fdd0, thd=0x7f0b10001040, qe=0x7f0b1000c7c0,
    result=@0x7f0b10020d58: 0x7f0b10021d28, setup_tables_done_option=0, res=@0x7f10240b1620: 0, optimize_after_tianmu=@0x7f10240b1690: 1,
    tianmu_free_join=@0x7f10240b1624: 1, with_insert=0) at /data/codebase/stonedb80/stonedb/storage/tianmu/core/engine.cpp:2194
#15 0x0000561546d283b1 in Tianmu::handler::ha_my_tianmu_query (thd=0x7f0b10001040, qe=0x7f0b1000c7c0, result=@0x7f0b10020d58: 0x7f0b10021d28,
    setup_tables_done_option=0, res=@0x7f10240b1620: 0, optimize_after_tianmu=@0x7f10240b1690: 1, tianmu_free_join=@0x7f10240b1624: 1, with_insert=0)
    at /data/codebase/stonedb80/stonedb/storage/tianmu/handler/ha_my_tianmu.cpp:92
#16 0x0000561544b68d9d in Sql_cmd_dml::execute (this=0x7f0b10020d30, thd=0x7f0b10001040) at /data/codebase/stonedb80/stonedb/sql/sql_select.cc:579
#17 0x0000561544adfcfb in mysql_execute_command (thd=0x7f0b10001040, first_level=true) at /data/codebase/stonedb80/stonedb/sql/sql_parse.cc:4604
#18 0x0000561544ae1fe6 in dispatch_sql_command (thd=0x7f0b10001040, parser_state=0x7f10240b2b90)
    at /data/codebase/stonedb80/stonedb/sql/sql_parse.cc:5239
#19 0x0000561544ad7a65 in dispatch_command (thd=0x7f0b10001040, com_data=0x7f10240b34e0, command=COM_QUERY)
    at /data/codebase/stonedb80/stonedb/sql/sql_parse.cc:1959
#20 0x0000561544ad5adc in do_command (thd=0x7f0b10001040) at /data/codebase/stonedb80/stonedb/sql/sql_parse.cc:1362
#21 0x0000561544d12415 in handle_connection (arg=0x56155085d840)
    at /data/codebase/stonedb80/stonedb/sql/conn_handler/connection_handler_per_thread.cc:302
#22 0x0000561546c3428a in pfs_spawn_thread (arg=0x56155089e9a0) at /data/codebase/stonedb80/stonedb/storage/perfschema/pfs.cc:2942
--Type <RET> for more, q to quit, c to continue without paging--
#23 0x00007f107baf9609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#24 0x00007f107aa04133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

**Comment by lujiashun** [comment]
issue475.test（result file changed from "2015-11-13 01:01:01.000020" to "2015-11-13 01:01:01.00002"）, stondb8.0 version after merged PR: #772 
```
(gdb) bt
#0  Item::get_date_from_string (this=0x7fe5cc02fb28, ltime=0x7fead45ec310, flags=1) at /data/codebase/stonedb80/stonedb/sql/item.cc:1418
#1  0x000055ffd088008f in Tianmu::types::Item_sum_hybrid_rcbase::get_date (this=0x7fe5cc02fb28, ltime=0x7fead45ec310, fuzzydate=1)
    at /data/codebase/stonedb80/stonedb/storage/tianmu/types/rc_item_types.h:118
#2  0x000055ffce8b9634 in Item::send (this=0x7fe5cc02fb28, protocol=0x7fe5cc005e60, buffer=0x7fead45ec3b0)
    at /data/codebase/stonedb80/stonedb/sql/item.cc:7308
#3  0x000055ffce36aa3c in THD::send_result_set_row (this=0x7fe5cc00cd10, row_items=...) at /data/codebase/stonedb80/stonedb/sql/sql_class.cc:2865
#4  0x000055ffceb2f46f in Query_result_send::send_data (this=0x7fe5cc02f308, thd=0x7fe5cc00cd10, items=...)
    at /data/codebase/stonedb80/stonedb/sql/query_result.cc:100
#5  0x000055ffd0783d3d in Tianmu::core::ResultSender::SendRecord (this=0x7fe5cc0086b0, r=std::vector of length 1, capacity 1 = {...})
    at /data/codebase/stonedb80/stonedb/storage/tianmu/core/engine_results.cpp:353
#6  0x000055ffd07836cb in Tianmu::core::ResultSender::SendRow (this=0x7fe5cc0086b0, record=std::vector of length 1, capacity 1 = {...},
    owner=0x7fe5cc03b590) at /data/codebase/stonedb80/stonedb/storage/tianmu/core/engine_results.cpp:260
#7  0x000055ffd0849b4d in Tianmu::core::TempTable::SendResult (this=0x7fe5cc03b590, limit=1, offset=0, sender=..., pagewise=false)
    at /data/codebase/stonedb80/stonedb/storage/tianmu/core/temp_table_low.cpp:482
#8  0x000055ffd084885e in Tianmu::core::TempTable::FillMaterializedBuffers (this=0x7fe5cc03b590, local_limit=1, local_offset=0, sender=0x7fe5cc0086b0,
    pagewise=false) at /data/codebase/stonedb80/stonedb/storage/tianmu/core/temp_table_low.cpp:310
#9  0x000055ffd0831275 in Tianmu::core::TempTable::Materialize (this=0x7fe5cc03b590, in_subq=false, sender=0x7fe5cc0086b0, lazy=false)
    at /data/codebase/stonedb80/stonedb/storage/tianmu/core/temp_table.cpp:1958
#10 0x000055ffd0748d01 in Tianmu::core::Engine::Execute (this=0x55ffd7c90540, thd=0x7fe5cc00cd10, lex=0x7fe5cc010020, result_output=0x7fe5cc02f308,
    unit_for_union=0x0) at /data/codebase/stonedb80/stonedb/storage/tianmu/core/engine.cpp:2345
#11 0x000055ffd0748014 in Tianmu::core::Engine::Handle_Query (this=0x55ffd7c90540, thd=0x7fe5cc00cd10, qe=0x7fe5cc02c6e0,
    result=@0x7fe5cc02f2f8: 0x7fe5cc02f308, setup_tables_done_option=0, res=@0x7fead45ed620: 0, optimize_after_tianmu=@0x7fead45ed690: 1,
    tianmu_free_join=@0x7fead45ed624: 1, with_insert=0) at /data/codebase/stonedb80/stonedb/storage/tianmu/core/engine.cpp:2192
#12 0x000055ffd069a3b1 in Tianmu::handler::ha_my_tianmu_query (thd=0x7fe5cc00cd10, qe=0x7fe5cc02c6e0, result=@0x7fe5cc02f2f8: 0x7fe5cc02f308,
    setup_tables_done_option=0, res=@0x7fead45ed620: 0, optimize_after_tianmu=@0x7fead45ed690: 1, tianmu_free_join=@0x7fead45ed624: 1, with_insert=0)
    at /data/codebase/stonedb80/stonedb/storage/tianmu/handler/ha_my_tianmu.cpp:92
#13 0x000055ffce4dad9d in Sql_cmd_dml::execute (this=0x7fe5cc02f2d0, thd=0x7fe5cc00cd10) at /data/codebase/stonedb80/stonedb/sql/sql_select.cc:579
#14 0x000055ffce451cfb in mysql_execute_command (thd=0x7fe5cc00cd10, first_level=true) at /data/codebase/stonedb80/stonedb/sql/sql_parse.cc:4604
#15 0x000055ffce453fe6 in dispatch_sql_command (thd=0x7fe5cc00cd10, parser_state=0x7fead45eeb90)
    at /data/codebase/stonedb80/stonedb/sql/sql_parse.cc:5239
#16 0x000055ffce449a65 in dispatch_command (thd=0x7fe5cc00cd10, com_data=0x7fead45ef4e0, command=COM_QUERY)
    at /data/codebase/stonedb80/stonedb/sql/sql_parse.cc:1959
#17 0x000055ffce447adc in do_command (thd=0x7fe5cc00cd10) at /data/codebase/stonedb80/stonedb/sql/sql_parse.cc:1362
#18 0x000055ffce684415 in handle_connection (arg=0x55ffd7d56a90)
    at /data/codebase/stonedb80/stonedb/sql/conn_handler/connection_handler_per_thread.cc:302
#19 0x000055ffd05a628a in pfs_spawn_thread (arg=0x55ffda39e110) at /data/codebase/stonedb80/stonedb/storage/perfschema/pfs.cc:2942
#20 0x00007feb478f9609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#21 0x00007feb46804133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) list
1413      String tmp(buff, sizeof(buff), &my_charset_bin), *res;
1414      if (!(res = val_str(&tmp))) {
1415        set_zero_time(ltime, MYSQL_TIMESTAMP_DATETIME);
1416        return true;
1417      }
1418      return str_to_datetime_with_warn(res, ltime, flags);
1419    }
1420
1421    bool Item::get_date_from_real(MYSQL_TIME *ltime, my_time_flags_t flags) {
1422      double value = val_real();
(gdb) p tmp
$5 = {m_ptr = 0x7fead45ec230 "", m_length = 36, m_charset = 0x55ffd3b26be0 <my_charset_bin>, m_alloced_length = 36, m_is_alloced = false}
(gdb) x/c tmp->m_ptr
0x7fead45ec230: 0 '\000'
(gdb) x/30c  tmp->m_ptr
0x7fead45ec230: 0 '\000'        -61 '\303'      94 '^'  -44 '\324'      -22 '\352'      127 '\177'      0 '\000'        0 '\000'
0x7fead45ec238: 88 'X'  -85 '\253'      121 'y' -47 '\321'      -1 '\377'       85 'U'  0 '\000'        0 '\000'
0x7fead45ec240: -86 '\252'      3 '\003'        0 '\000'        0 '\000'        14 '\016'       0 '\000'        0 '\000'        0 '\000'
0x7fead45ec248: -104 '\230'     -50 '\316'      2 '\002'        -52 '\314'      -27 '\345'      127 '\177'
(gdb) p sizeof(buff)
$6 = 36
(gdb) x/38c  tmp->m_ptr
0x7fead45ec230: 0 '\000'        -61 '\303'      94 '^'  -44 '\324'      -22 '\352'      127 '\177'      0 '\000'        0 '\000'
0x7fead45ec238: 88 'X'  -85 '\253'      121 'y' -47 '\321'      -1 '\377'       85 'U'  0 '\000'        0 '\000'
0x7fead45ec240: -86 '\252'      3 '\003'        0 '\000'        0 '\000'        14 '\016'       0 '\000'        0 '\000'        0 '\000'
0x7fead45ec248: -104 '\230'     -50 '\316'      2 '\002'        -52 '\314'      -27 '\345'      127 '\177'      0 '\000'        0 '\000'
0x7fead45ec250: -128 '\200'     -62 '\302'      94 '^'  -44 '\324'      -22 '\352'      127 '\177'
(gdb) n
1413      String tmp(buff, sizeof(buff), &my_charset_bin), *res;
(gdb) n
1419    }
(gdb) p tmp
$7 = {m_ptr = 0x7fead45ec230 "", m_length = 36, m_charset = 0x55ffd3b26be0 <my_charset_bin>, m_alloced_length = 36, m_is_alloced = false}
(gdb) p res
$8 = (String *) 0x7fe5cc02fc60
(gdb) p *res
$9 = {m_ptr = 0x7fe5cc0079a0 "2015-11-13 01:01:01.000020", m_length = 26, m_charset = 0x55ffd3b2fce0 <my_charset_latin1>, m_alloced_length = 32,
```


```
(gdb) bt
#0  Protocol_text::store_datetime (this=0x7fe5cc005e60, tm=..., decimals=5) at /data/codebase/stonedb80/stonedb/sql/protocol_classic.cc:3623
#1  0x000055ffce8b9683 in Item::send (this=0x7fe5cc02fb28, protocol=0x7fe5cc005e60, buffer=0x7fead45ec3b0)
    at /data/codebase/stonedb80/stonedb/sql/item.cc:7309
#2  0x000055ffce36aa3c in THD::send_result_set_row (this=0x7fe5cc00cd10, row_items=...) at /data/codebase/stonedb80/stonedb/sql/sql_class.cc:2865
#3  0x000055ffceb2f46f in Query_result_send::send_data (this=0x7fe5cc02f308, thd=0x7fe5cc00cd10, items=...)
    at /data/codebase/stonedb80/stonedb/sql/query_result.cc:100
#4  0x000055ffd0783d3d in Tianmu::core::ResultSender::SendRecord (this=0x7fe5cc0086b0, r=std::vector of length 1, capacity 1 = {...})
    at /data/codebase/stonedb80/stonedb/storage/tianmu/core/engine_results.cpp:353
#5  0x000055ffd07836cb in Tianmu::core::ResultSender::SendRow (this=0x7fe5cc0086b0, record=std::vector of length 1, capacity 1 = {...},
    owner=0x7fe5cc03b590) at /data/codebase/stonedb80/stonedb/storage/tianmu/core/engine_results.cpp:260
#6  0x000055ffd0849b4d in Tianmu::core::TempTable::SendResult (this=0x7fe5cc03b590, limit=1, offset=0, sender=..., pagewise=false)
    at /data/codebase/stonedb80/stonedb/storage/tianmu/core/temp_table_low.cpp:482
#7  0x000055ffd084885e in Tianmu::core::TempTable::FillMaterializedBuffers (this=0x7fe5cc03b590, local_limit=1, local_offset=0, sender=0x7fe5cc0086b0,
    pagewise=false) at /data/codebase/stonedb80/stonedb/storage/tianmu/core/temp_table_low.cpp:310
#8  0x000055ffd0831275 in Tianmu::core::TempTable::Materialize (this=0x7fe5cc03b590, in_subq=false, sender=0x7fe5cc0086b0, lazy=false)
    at /data/codebase/stonedb80/stonedb/storage/tianmu/core/temp_table.cpp:1958
#9  0x000055ffd0748d01 in Tianmu::core::Engine::Execute (this=0x55ffd7c90540, thd=0x7fe5cc00cd10, lex=0x7fe5cc010020, result_output=0x7fe5cc02f308,
    unit_for_union=0x0) at /data/codebase/stonedb80/stonedb/storage/tianmu/core/engine.cpp:2345
#10 0x000055ffd0748014 in Tianmu::core::Engine::Handle_Query (this=0x55ffd7c90540, thd=0x7fe5cc00cd10, qe=0x7fe5cc02c6e0,
    result=@0x7fe5cc02f2f8: 0x7fe5cc02f308, setup_tables_done_option=0, res=@0x7fead45ed620: 0, optimize_after_tianmu=@0x7fead45ed690: 1,
    tianmu_free_join=@0x7fead45ed624: 1, with_insert=0) at /data/codebase/stonedb80/stonedb/storage/tianmu/core/engine.cpp:2192
#11 0x000055ffd069a3b1 in Tianmu::handler::ha_my_tianmu_query (thd=0x7fe5cc00cd10, qe=0x7fe5cc02c6e0, result=@0x7fe5cc02f2f8: 0x7fe5cc02f308,
    setup_tables_done_option=0, res=@0x7fead45ed620: 0, optimize_after_tianmu=@0x7fead45ed690: 1, tianmu_free_join=@0x7fead45ed624: 1, with_insert=0)
    at /data/codebase/stonedb80/stonedb/storage/tianmu/handler/ha_my_tianmu.cpp:92
#12 0x000055ffce4dad9d in Sql_cmd_dml::execute (this=0x7fe5cc02f2d0, thd=0x7fe5cc00cd10) at /data/codebase/stonedb80/stonedb/sql/sql_select.cc:579
#13 0x000055ffce451cfb in mysql_execute_command (thd=0x7fe5cc00cd10, first_level=true) at /data/codebase/stonedb80/stonedb/sql/sql_parse.cc:4604
#14 0x000055ffce453fe6 in dispatch_sql_command (thd=0x7fe5cc00cd10, parser_state=0x7fead45eeb90)
    at /data/codebase/stonedb80/stonedb/sql/sql_parse.cc:5239
#15 0x000055ffce449a65 in dispatch_command (thd=0x7fe5cc00cd10, com_data=0x7fead45ef4e0, command=COM_QUERY)
    at /data/codebase/stonedb80/stonedb/sql/sql_parse.cc:1959
#16 0x000055ffce447adc in do_command (thd=0x7fe5cc00cd10) at /data/codebase/stonedb80/stonedb/sql/sql_parse.cc:1362
#17 0x000055ffce684415 in handle_connection (arg=0x55ffd7d56a90)
    at /data/codebase/stonedb80/stonedb/sql/conn_handler/connection_handler_per_thread.cc:302
#18 0x000055ffd05a628a in pfs_spawn_thread (arg=0x55ffda39e110) at /data/codebase/stonedb80/stonedb/storage/perfschema/pfs.cc:2942
#19 0x00007feb478f9609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#20 0x00007feb46804133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

**Comment by lujiashun** [comment]
```
int my_datetime_to_str(const MYSQL_TIME &my_time, char *to, uint dec) {
  int len = TIME_to_datetime_str(my_time, to);
  if (dec) len += **my_useconds_to_str(to + len, my_time.second_part, dec);**
  if (my_time.time_type == MYSQL_TIMESTAMP_DATETIME_TZ) {
    int tzd = my_time.time_zone_displacement;
    len += sprintf(to + len, "%+02i:%02i", tzd / SECS_PER_HOUR,
                   std::abs(tzd) / SECS_PER_MIN % MINS_PER_HOUR);
  } else
    to[len] = '\0';
  return len;
}
```

**Comment by lujiashun** [comment]
issue475.test, in stonedb5.7
mysql5.7： have not fix the decimals，use default value 31，longer than 6， use 6， the acutal decimals value should be 5；
and conflicts with  the manual "An optional fsp value in the range from 0 to 6 may be given to specify fractional seconds precision";  
ref：https://dev.mysql.com/doc/refman/5.7/en/date-and-time-type-syntax.html
```
(gdb) bt
#0  my_datetime_to_str (l_time=0xb3c18, to=0xecfb9b24d <error: Cannot access memory at address 0xecfb9b24d>, dec=0)
    at /data/codebase/stonedb/sql-common/my_time.c:1301
#1  0x0000562d1cb86270 in my_TIME_to_str (l_time=0x7fc4ac964a50, to=0x7fc4ac964c50 "pL\226\254\304\177", dec=6)
    at /data/codebase/stonedb/sql-common/my_time.c:1326
#2  0x0000562d1caf91e6 in my_TIME_to_str (ltime=0x7fc4ac964a50, str=0x7fc4ac964bf0, dec=6) at /data/codebase/stonedb/sql/sql_time.cc:1203
#3  0x0000562d1c8f19a9 in Item_temporal_hybrid_func::val_str_ascii (this=0x7fbf98151c20, str=0x7fc4ac964bf0)
    at /data/codebase/stonedb/sql/item_timefunc.cc:940
#4  0x0000562d1c8b92a5 in Item_str_func::val_str_from_val_str_ascii (this=0x7fbf98151c20, str=0x7fc4ac964bf0, str2=0x7fbf98151d08)
    at /data/codebase/stonedb/sql/item_strfunc.cc:89
#5  0x0000562d1c8fb46a in Item_temporal_hybrid_func::val_str (this=0x7fbf98151c20, str=0x7fc4ac964bf0) at /data/codebase/stonedb/sql/item_timefunc.h:630
#6  0x0000562d1c369d51 in Item::send (this=0x7fbf98151c20, protocol=0x7fbf98014008, buffer=0x7fc4ac964bf0) at /data/codebase/stonedb/sql/item.cc:7541
#7  0x0000562d1c9eb04c in THD::send_result_set_row (this=0x7fbf98012e60, row_items=0x7fbf98150d68) at /data/codebase/stonedb/sql/sql_class.cc:4757
#8  0x0000562d1c9e4f23 in Query_result_send::send_data (this=0x7fbf981524e8, items=...) at /data/codebase/stonedb/sql/sql_class.cc:2742
#9  0x0000562d1ca042c5 in end_send (join=0x7fbf981526a8, qep_tab=0x7fbf98001fc8, end_of_records=false)
    at /data/codebase/stonedb/sql/sql_executor.cc:2936
#10 0x0000562d1ca00cdd in evaluate_join_record (join=0x7fbf981526a8, qep_tab=0x7fbf98001e50) at /data/codebase/stonedb/sql/sql_executor.cc:1652
#11 0x0000562d1ca00077 in sub_select (join=0x7fbf981526a8, qep_tab=0x7fbf98001e50, end_of_records=false)
    at /data/codebase/stonedb/sql/sql_executor.cc:1304
#12 0x0000562d1c9ff85b in do_select (join=0x7fbf981526a8) at /data/codebase/stonedb/sql/sql_executor.cc:957
#13 0x0000562d1c9fd5ee in JOIN::exec (this=0x7fbf981526a8) at /data/codebase/stonedb/sql/sql_executor.cc:206
#14 0x0000562d1caa03cc in handle_query (thd=0x7fbf98012e60, lex=0x7fbf98015188, result=0x7fbf981524e8, added_options=0, removed_options=0,
    optimize_after_bh=0, free_join_from_bh=0) at /data/codebase/stonedb/sql/sql_select.cc:195
#15 0x0000562d1ca4ff50 in execute_sqlcom_select (thd=0x7fbf98012e60, all_tables=0x7fbf98151ea0) at /data/codebase/stonedb/sql/sql_parse.cc:5184
#16 0x0000562d1ca48fa5 in mysql_execute_command (thd=0x7fbf98012e60, first_level=true) at /data/codebase/stonedb/sql/sql_parse.cc:2831
#17 0x0000562d1ca50fa4 in mysql_parse (thd=0x7fbf98012e60, parser_state=0x7fc4ac9665f0) at /data/codebase/stonedb/sql/sql_parse.cc:5621
#18 0x0000562d1ca45c61 in dispatch_command (thd=0x7fbf98012e60, com_data=0x7fc4ac966ea0, command=COM_QUERY)
    at /data/codebase/stonedb/sql/sql_parse.cc:1495
#19 0x0000562d1ca44ad8 in do_command (thd=0x7fbf98012e60) at /data/codebase/stonedb/sql/sql_parse.cc:1034
#20 0x0000562d1cb8d276 in handle_connection (arg=0x562d23add810) at /data/codebase/stonedb/sql/conn_handler/connection_handler_per_thread.cc:313
#21 0x0000562d1d2d7275 in pfs_spawn_thread (arg=0x562d23866990) at /data/codebase/stonedb/storage/perfschema/pfs.cc:2197
#22 0x00007fc4b3d42609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#23 0x00007fc4b3b16133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by lujiashun** [comment]
issue475.test, stonedb8.0： How to fix the decimal size

```
(gdb) c
Continuing.

Thread 131 "connection" hit Hardware watchpoint 9: *(uint8 *) 0x7fe5cc02e1b8

Old value = 0 '\000'
New value = 5 '\005'
Item::set_data_type_datetime (this=0x7fe5cc02e130, fsp=5 '\005') at /data/codebase/stonedb80/stonedb/sql/item.h:1504
1504        max_length = MAX_DATETIME_WIDTH + fsp + (fsp > 0 ? 1 : 0);
(gdb) bt
#0  Item::set_data_type_datetime (this=0x7fe5cc02e130, fsp=5 '\005') at /data/codebase/stonedb80/stonedb/sql/item.h:1504
#1  0x000055ffcea08a3e in Item_func_add_time::resolve_type (this=0x7fe5cc02e130, thd=0x7fe5cc00cd10)
    at /data/codebase/stonedb80/stonedb/sql/item_timefunc.cc:3022
#2  0x000055ffce93e5f4 in Item_func::fix_fields (this=0x7fe5cc02e130, thd=0x7fe5cc00cd10) at /data/codebase/stonedb80/stonedb/sql/item_func.cc:420
#3  0x000055ffce99d750 in Item_str_func::fix_fields (this=0x7fe5cc02e130, thd=0x7fe5cc00cd10, ref=0x7fe5cc02e650)
    at /data/codebase/stonedb80/stonedb/sql/item_strfunc.cc:164
#4  0x000055ffce348497 in setup_fields (thd=0x7fe5cc00cd10, want_privilege=1, allow_sum_func=true, split_sum_funcs=true, column_update=false,
    typed_items=0x0, fields=0x7fe5cc02ce98, ref_item_array=...) at /data/codebase/stonedb80/stonedb/sql/sql_base.cc:9038
#5  0x000055ffce4a9391 in Query_block::prepare (this=0x7fe5cc02ce90, thd=0x7fe5cc00cd10, insert_field_list=0x0)
    at /data/codebase/stonedb80/stonedb/sql/sql_resolver.cc:274
#6  0x000055ffce4da791 in Sql_cmd_select::prepare_inner (this=0x7fe5cc02f2d0, thd=0x7fe5cc00cd10)
    at /data/codebase/stonedb80/stonedb/sql/sql_select.cc:480
#7  0x000055ffce4da18e in Sql_cmd_dml::prepare (this=0x7fe5cc02f2d0, thd=0x7fe5cc00cd10) at /data/codebase/stonedb80/stonedb/sql/sql_select.cc:397
#8  0x000055ffce4daa49 in Sql_cmd_dml::execute (this=0x7fe5cc02f2d0, thd=0x7fe5cc00cd10) at /data/codebase/stonedb80/stonedb/sql/sql_select.cc:535
#9  0x000055ffce451cfb in mysql_execute_command (thd=0x7fe5cc00cd10, first_level=true) at /data/codebase/stonedb80/stonedb/sql/sql_parse.cc:4604
#10 0x000055ffce453fe6 in dispatch_sql_command (thd=0x7fe5cc00cd10, parser_state=0x7fead45eeb90)
    at /data/codebase/stonedb80/stonedb/sql/sql_parse.cc:5239
#11 0x000055ffce449a65 in dispatch_command (thd=0x7fe5cc00cd10, com_data=0x7fead45ef4e0, command=COM_QUERY)
    at /data/codebase/stonedb80/stonedb/sql/sql_parse.cc:1959
#12 0x000055ffce447adc in do_command (thd=0x7fe5cc00cd10) at /data/codebase/stonedb80/stonedb/sql/sql_parse.cc:1362
#13 0x000055ffce684415 in handle_connection (arg=0x55ffd7d56a90)
    at /data/codebase/stonedb80/stonedb/sql/conn_handler/connection_handler_per_thread.cc:302
#14 0x000055ffd05a628a in pfs_spawn_thread (arg=0x55ffda39e110) at /data/codebase/stonedb80/stonedb/storage/perfschema/pfs.cc:2942
#15 0x00007feb478f9609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#16 0x00007feb46804133 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
