### ISSUE TITLE
bug: Query result set error，varchar(255) The result of adding data is not queried

### ISSUE THREAD

**Issue by shangyanwen** [stoneatom/stonedb#959]
### Have you read the Contributing Guidelines on issues?

- [X] I have read the [Contributing Guidelines on issues](https://github.com/stoneatom/stonedb/blob/stonedb-5.7-dev/CONTRIBUTING.md).

### Please confirm if bug report does NOT exists already ?

- [X] I confirm there is no existing issue for this

### Describe the problem

```
CREATE TABLE device_delta_collect
(
    reportTime varchar(255) DEFAULT NULL,
    deviceId   varchar(255) DEFAULT NULL,
    multiple   varchar(255) DEFAULT NULL,
    deltaJgs   varchar(255) DEFAULT NULL
) ENGINE = tianmu;

insert into device_delta_collect (reportTime, deviceId, deltaJgs, multiple) values ('2022-08-20 22:33:58', '1547034559760195585', '1', '1');

select * from device_delta_collect a where a.deviceId = 1547034559760195587 limit 10;
Empty set (0.00 sec)
```

### Expected behavior

MySQL(innodb) results:
```
mysql> select * from device_delta_collect a where a.deviceId = 1547034559760195587 limit 10;
+---------------------+---------------------+----------+----------+
| reportTime          | deviceId            | multiple | deltaJgs |
+---------------------+---------------------+----------+----------+
| 2022-08-20 22:33:58 | 1547034559760195585 | 1        | 1        |
+---------------------+---------------------+----------+----------+
```

### How To Reproduce

```
CREATE TABLE device_delta_collect
(
    reportTime varchar(255) DEFAULT NULL,
    deviceId   varchar(255) DEFAULT NULL,
    multiple   varchar(255) DEFAULT NULL,
    deltaJgs   varchar(255) DEFAULT NULL
) ENGINE = tianmu;

insert into device_delta_collect (reportTime, deviceId, deltaJgs, multiple) values ('2022-08-20 22:33:58', '1547034559760195585', '1', '1');

select * from device_delta_collect a where a.deviceId = 1547034559760195587 limit 10;
```

### Environment

```
root@ub01:/stonedb57/install/bin# ./mysql --version
./mysql  Ver 14.14 Distrib 5.7.36-StoneDB, for Linux (x86_64) using  EditLine wrapper
```

### Are you interested in submitting a PR to solve the problem?

- [ ] Yes, I will!

**Comment by adofsauron** [comment]
ACK

**Comment by adofsauron** [comment]
### Compare INNODB's handling

![409C9580-FD93-4111-9722-627A4195A547](https://user-images.githubusercontent.com/3915817/204177406-b3bdde82-df9e-4ab5-abfe-1d8b8da30b16.png)


![image](https://user-images.githubusercontent.com/3915817/204177157-4c0bb56c-386c-4f40-966e-91da2f1fbf48.png)



```c++

(gdb) layout src
(gdb) bt
#0  Item_int::val_real (this=0x7f6bcc000fc8) at item.h:1211
#1  0x00000000004e5ac2 in Arg_comparator::compare_real (this=0x7f6bcc0010e0) at item_cmpfunc.cc:403
#2  0x00000000004e3cf0 in compare (this=<optimized out>) at item_cmpfunc.h:59
#3  Item_func_eq::val_int (this=<optimized out>) at item_cmpfunc.cc:719
#4  0x0000000000572365 in evaluate_join_record (join=join@entry=0x7f6bcc001258, join_tab=join_tab@entry=0x7f6bcc0146e0, error=<optimized out>, report_error=report_error@entry=0x27d82e0 "")
    at sql_select.cc:8588
#5  0x000000000057259c in sub_select (join=join@entry=0x7f6bcc001258, join_tab=0x7f6bcc0146e0, end_of_records=end_of_records@entry=false) at sql_select.cc:8545
#6  0x0000000000579b3d in do_select (join=join@entry=0x7f6bcc001258, fields=fields@entry=0x27d7790, table=table@entry=0x0, procedure=0x0) at sql_select.cc:8311
#7  0x0000000000587d1c in JOIN::exec (this=this@entry=0x7f6bcc001258) at sql_select.cc:1436
#8  0x000000000058349a in mysql_select (thd=thd@entry=0x27d72a0, rref_pointer_array=rref_pointer_array@entry=0x27d78c8, tables=0x7f6bcc000c20, wild_num=<optimized out>, fields=..., 
    conds=<optimized out>, og_num=0, order=0x0, group=0x0, having=0x0, proc_param=0x0, select_options=select_options@entry=2156153344, result=result@entry=0x7f6bcc001238, unit=unit@entry=0x27d7320, 
    select_lex=select_lex@entry=0x27d76a0) at sql_select.cc:1591
#9  0x0000000000583674 in handle_select (thd=thd@entry=0x27d72a0, lex=lex@entry=0x27d7308, result=result@entry=0x7f6bcc001238, setup_tables_done_option=setup_tables_done_option@entry=0)
    at sql_select.cc:186
#10 0x000000000054269d in mysql_execute_command (thd=thd@entry=0x27d72a0) at sql_parse.cc:2298
#11 0x00000000005428d7 in mysql_parse (thd=thd@entry=0x27d72a0, inBuf=<optimized out>, length=<optimized out>) at sql_parse.cc:5101
#12 0x00000000005435dc in dispatch_command (command=command@entry=COM_QUERY, thd=thd@entry=0x27d72a0, packet=packet@entry=0x27f3131 "", packet_length=packet_length@entry=85) at sql_parse.cc:1579
#13 0x00000000005446f8 in do_command (thd=0x27d72a0) at sql_parse.cc:1386
#14 0x00000000005451ea in handle_one_connection (arg=<optimized out>) at sql_parse.cc:1043
#15 0x00007f6be4b18ea5 in start_thread () from /lib64/libpthread.so.0
#16 0x00007f6be39ccb0d in clone () from /lib64/libc.so.6

```



```c++

(gdb) p value
$10 = 1547034559760195587
(gdb) p	(double)value
$11 = 1.5470345597601956e+18

```

**Comment by adofsauron** [comment]
### Compare the treatment of TIANMU
![8B27882C-3E1F-4205-8BA3-B32D1E1CC125](https://user-images.githubusercontent.com/3915817/204181134-e929edd2-04ee-4e79-bbe4-b63d574a665b.png)
